### ISSUE TITLE
MicrosoftTeams module requires NuGet

### ISSUE THREAD

**Issue by 66redfeather99** [PowerShell/PowerShellGallery#104]
The page at https://www.powershellgallery.com/packages/MicrosoftTeams/1.0.6 kindly describes how to start installing PowerShell tools required to interact with Microsoft Teams. It says "no dependencies," and this is not really a dependency of the package itself, but Install-Module -Name MicrosoftTeams returns "NuGet provider is required to continue." I think this expectation should be added to the page, especially since the response above specifies that NuGet is untrusted.

**Comment by SydneyhSmith** [comment]
Thanks @66redfeather99 this issue would be best for the team that owns the Microsoft Teams module...based on the module page it looks like their repo is here: https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams
