### ISSUE TITLE
Remove Political Statements from Website

### ISSUE THREAD

**Issue by cjhprimus** [PowerShell/PowerShellGallery#109]
At the top of the https://www.powershellgallery.com/ site, is a banner that simply reads "Black Lives Matter".  This appears to be an explicit endorsement of a Marxist organization "Black Lives Matter" which promotes, among other things the idea that we must "disrupt the Western-prescribed nuclear family structure". 

Any kind of political advocacy is out of place for a non-political organization like the PowerShell Gallery, which simply hosts modules for the global PowerShell community.  By opening yourself up to this political advocacy you now risk criticism in the future for "incorrectly" advocating (or failing to advocate for) the next political cause anywhere in the world. 

Please remove all political statements and opinions.

**Comment by jasonrpitts** [comment]
I concur with this request. This site is not the place to promote domestic terrorist organizations.

**Comment by TylerLeonhardt** [comment]
Thanks for the feedback. However, Microsoft has an official stance on this topic https://blogs.microsoft.com/blog/2020/06/23/addressing-racial-injustice/.

Saying “Black Lives Matter” does not mean “Only Black Lives Matter”; it means “Black Lives Also Matter”. There are many sources on this, but here is just the first I found on a web search: https://www.msn.com/en-us/news/us/black-lives-matter-vs-all-lives-matter-what-we-say-matters/ar-BB15l4L4.

I also recommend watching the documentary called 13th [which is available for free on YouTube](https://youtu.be/krfcq5pF8u8).

Certainly there are some bad actors taking advantage of the recent protests and movements, but that should not be confused with the intent of Black Lives Matter.
