### ISSUE TITLE
Please remove promotion of domestic terror organizations from this website. It is not appropriate.

### ISSUE THREAD

**Issue by jasonrpitts** [PowerShell/PowerShellGallery#110]
At the top of the Powershell Gallery was a "Black Lives Matter" message in apparent promotion of the US terror organization of the same name. Please refrain from placing such advertisements for that and similar organizations on this technical website.

**Comment by TylerLeonhardt** [comment]
Please see my response here:
https://github.com/PowerShell/PowerShellGallery/issues/109#issuecomment-658561907
