### ISSUE TITLE
Broken Link for Azure Automation Learn More

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/PowerShellGallery#114]
## Overview

When viewing a package on the PowerShell Gallery, there is a **Learn more** link on the **Azure Automation** tab. That link is a vanity URL (https://aka.ms/PSGalleryToAzureAutomation) that resolves to a resource that no longer exists resulting in a HTTP 404 error.

It appears the issues is caused by a change to the directory structure of the PowerShell documentation where a `scripting` directory has been added.

### Incorrect Link

https://docs.microsoft.com/en-us/powershell/gallery/how-to/working-with-packages/deploy-to-azure-automation

### Correct Link

https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/deploy-to-azure-automation

**Comment by SydneyhSmith** [comment]
Thanks @bmkaiser I will notify the link owner

**Comment by SydneyhSmith** [comment]
Should be fixed now
