### ISSUE TITLE
Where is the MicrosoftTeams package?

### ISSUE THREAD

**Issue by janningwingcopter** [PowerShell/PowerShellGallery#115]
![grafik](https://user-images.githubusercontent.com/57598677/89647214-7ca79f00-d8bd-11ea-9dbb-269b03e905a2.png)

**Comment by glasekadrian** [comment]
Microsoft team package still missing.

**Comment by SydneyhSmith** [comment]
Looks like you are using the wrong gallery---that is our internal test gallery. The package can be found on the public site: https://www.powershellgallery.com/packages/MicrosoftTeams/1.1.4
