### ISSUE TITLE
Are download statistics broken or backlogged?

### ISSUE THREAD

**Issue by rmbolger** [PowerShell/PowerShellGallery#124]
I released a new version of some modules the other day and the download statistics don't seem to be increasing even after personally downloading the module. The [View Full Stats](https://www.powershellgallery.com/stats/packages/Posh-ACME.net46?groupby=Version) page also claims `Statistics last updated at 2020-08-23 22:08:31 UTC.`

Is there something wrong site-wide with statistics gathering or is it just me?

**Comment by lahell** [comment]
Not just you. I came here to report the same issue.

**Comment by BanterBoy** [comment]
You are definitely not alone in this. None of the modules that either I or my friend have published have any updated statistics for some time.

This is more obvious with modules published in the last week, as although I know downloads have occurred, they are still reporting zero downloads.

There has been an issue with the statistics for the last couple of months, which I originally reported to the PowerShell Gallery team on the 29th June.

The original issue advised that there was a discrepancy between Module page statistics and the "Full Stats" as neither were displaying the same stats. 

I was advised:
>We figure out, our stats pipeline is broken. The count in the view full stats page is corrupted. We will fix it asap.

This issue has still not been resolved and appears to have gotten worse and as @rmbolger has noted, the full stats last updated date is no longer the previous day. eg **Statistics last updated at 2020-08-26 06:08:44 UTC.**

Seems to be a much bigger problem now but I suspect not many people have noticed yet.

Hope someone does something about it soon.

**Comment by trossr32** [comment]
Another upvote for this, I'm experiencing the same issue

**Comment by adamedx** [comment]
Looks like today we are starting to see **too many** downloads rather than none.

I was pleasantly surprised to see that my total downloads count had gone from 617 when I looked this morning to 16000 this afternoon! :) Of course, given the yellow download stats issue notice at the top of the gallery I had to assume a fix for that issue might have inflated my download count just *slightly*. On closer inspection, all of my completely out of date versions had ridiculously high download counts that had not been there before, and other modules in the gallery had count jumps between their recent versions of multiple orders of magnitude.

So it appears to be a widespread problem possibly related to an attempt to fix things, a backfill gone awry. I think this is actually worse than just losing a few weeks worth of stats, but even if we can't roll back, I do hope the madness eventually stops.

There are worse problems in the world though...

**Comment by lahell** [comment]
Same here. Older versions of my modules have unlikely high download counts and the new versions published three days ago still have zero downloads.

**Comment by CalebAlbers** [comment]
I can also confirm - one of my modules went from 600k downloads to 57 Million downloads within a week. As much as I'd love to dream that's true, clearly there's something awry 🙂

**Comment by whiteken** [comment]
Found this thread because of similar suspicions on my module... ~7000+ downloads in a week!  Knew something must have been amiss.

**Comment by MichaelGrafnetter** [comment]
This seems to be fixed now. But we have yet another issue with statistics of all packages:
![image](https://user-images.githubusercontent.com/8986376/97074376-48509e80-15e1-11eb-8a0d-4fcee0c3a168.png)

**Comment by adamedx** [comment]
Seems like the issue has returned. Around 10/19, my download count seemed to have been restored to what it was before the "inflation." Versions published after that had a count of zero, but started to show a few downloads later in the week at a realistic rate. This morning the count was the same as it was yesterday evening, but now a few hours later there have been 100+ downloads -- I usually get no more than 2 a day. There's some evidence that there's been more traffic to my site, but nothing that would explain this rate, and checking back an hour later showed 10 more.

Perhaps this is an attempt to backfill lost downloads from the period of several weeks where the statistics were broken? Given that this issue remains open, maybe there's still work going on to restore downloads that might have occurred during the outage. But in my case even this seems like an excessive amount; I would be happy with just losing weeks of stats if I could trust the stats moving forward.

**Comment by vpopescu** [comment]
Is there an official tracking thread for the statistics issue? The yellow "We are working on fixing the broken package statistics page" has been there seemingly forever now. Can't be that hard to fix it.

**Comment by trossr32** [comment]
The yellow banner has now been removed but the numbers look low. If this has been resolved could we have a brief update as to what the resolution was? Have stats been rolled back to a certain point in time and will now increment correctly again?

**Comment by o-l-a-v** [comment]
@trossr32 

https://devblogs.microsoft.com/powershell/incident-report-powershell-gallery-downtime-october-30-2020/

**Comment by vpopescu** [comment]
![image](https://user-images.githubusercontent.com/7304633/154767670-d1380f3f-0f0b-4121-9c43-c274b4c2b25c.png)

Today is 2/18/2022.

Just saying, Microsoft.

**Comment by mikenelson-io** [comment]
Almost 2023 and it still says 12/4/2020. C'mon folks. 
![image](https://user-images.githubusercontent.com/6254544/201411421-d6daaa3e-4355-4ae0-99e7-b19e1394b0fe.png)

**Comment by anamnavi** [comment]
We are aware and understand the frustration regarding this and are looking into this but unfortunately don't have a definitive answer for when it'll be resolved by.

**Comment by anamnavi** [comment]
Updates are being posted in this similar issue here: https://github.com/PowerShell/PowerShellGallery/issues/242
