### ISSUE TITLE
Could you provider Firewall Rule

### ISSUE THREAD

**Issue by kkbruce** [PowerShell/PowerShellGallery#126]
In Intranet need setup Firewall to access the Internet.

Example run `Install-Module -Name SqlServer` in Intranet:

![image](https://user-images.githubusercontent.com/2024682/93551397-55ee8500-f9a0-11ea-966a-6aa48e89ea27.png)

Could you provide the Firewall Rule? (If possible)

**Comment by hjorslev** [comment]
Have you considered using [Save-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/save-module?view=powershell-7) to save the module locally on another machine and then copy the saved module to the server?

**Comment by fatmanadiah-ship-it** [comment]
Yes, but need to pay the God Ordered!! Then keep promise to bring hudud after that. Let's the angels control all or we can take it personal, then pay the God ordered, Thank God.. Insya Allah, Amen..

**Comment by kkbruce** [comment]
@hjorslev 

After testing, I think this is a good alternative. Especially in a limited network environment. Thank you.
