### ISSUE TITLE
Cannot access Powershell AzureADPreview???

### ISSUE THREAD

**Issue by myatix** [PowerShell/PowerShellGallery#133]
Hi,
I have just tried to install AzureADPreview and the server is returning an internal 500 error?

Please fix! :)

**Comment by serxansherif** [comment]
hi @myatix 
Powershell gallery service has a problem. I'm not able to also install any module.

**Comment by alerickson** [comment]
Hi, this issue should be mitigated now, but please keep us updated if the low availability persists.  We're tracking this issue here: #132
