### ISSUE TITLE
Powershell Gallery is returning 503

### ISSUE THREAD

**Issue by kyanha** [PowerShell/PowerShellGallery#135]
Powershell Gallery is returning 503. I can't currently run https://github.com/powershell/powershell tests because they try to pull Pester from it.

**Comment by dariuszparys** [comment]
Same here with Pester and other modules

**Comment by ChristofStadler** [comment]
Having similar problem installing PSScriptTools, our build pipelines failing as a result.

**Comment by amorvillier** [comment]
Same behavior on my side

**Comment by mbrownphotouk** [comment]
I am getting a 503 error when trying to pull any modules down at the moment

**Comment by atyourservers** [comment]
Modules cannot be pulled from the PowerShell Gallery at the moment. The PowerShell Gallery seems to be unavailable for at least a few hours already.

**Comment by GGJason** [comment]
Is there any official websites for PowerShell Gallery status?
It is hard to know that it is down or just an internet error.

**Comment by mbrownphotouk** [comment]
https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md

Although nothing on there as yet for this

**Comment by alerickson** [comment]
Hi all, we currently have an outage and are working on resolving it.  Our CDN is down preventing packages from being downloaded and availability for the gallery itself has been extremely low.  I'll update here as mitigation steps progress.

**Comment by Creddi** [comment]
Same problem here

**Comment by o-l-a-v** [comment]
PowerShellGallery has become a essential resource for many. It's been unstable and have had other problems for months.

@alerickson : Is Microsoft comitting to making PowerShellGallery a reliable resource for PowerShell modules in **near** future, or do we have to look for other solutions (like GitHub maybe) for reliably hosting PowerShell modules?

**Comment by staedter** [comment]
> PowerShellGallery has become a essential resource for many. It's been unstable and have had other problems for months.
> 
> @alerickson : Is Microsoft comitting to making PowerShellGallery a reliable resource for PowerShell modules in **near** future, or do we have to look for other solutions (like GitHub maybe) for reliably hosting PowerShell modules?

I want to second the sentiment. Our CI/CD Pipelines quite heavily rely on the availability of multiple third-party modules that are primarily hosted on PS Gallery... I guess we should try to get rid of that single point of failure but Microsoft also should be doing more to guaranty the availability of something so vital to a lot of people.

Although I personally appreciate that @alerickson gave us the first official information about the problem from the responsible team from Microsoft, I think they should be doing a better job at communicating outages and mitigation progress than replying on Github issues.

**Comment by mbrownphotouk** [comment]
I concur I have a change which is reliant on me pulling a module down to a new server so this is eating away at my change window.

**Comment by jaskaran915** [comment]
facing same issue. Our ADO pipelines relies on powershell gallery for ps module. when we can aspect fix. Same kind of issue was observed few days back, but it was fixed by India Noon time on that day.

**Comment by isoengas** [comment]
Same here..

**Comment by TGosselink** [comment]
Same here. Need to install Docker on a new server and therefore need psgallery to install my modules. Can't work on this server now..

**Comment by RemkoD** [comment]
Same issue here (Netherlands).

**Comment by GGJason** [comment]
> 
> 
> https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md
> 
> Although nothing on there as yet for this

I think this page is for history now...

**Comment by smorenburg** [comment]
Same here, our pipelines came to a halt.

**Comment by staedter** [comment]
> > https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md
> > Although nothing on there as yet for this
> 
> I think this page is for history now...

Yes and apparently the only person on the team that thinks about informing users has no way of updating the repo

>The gallery's been experiencing ongoing low availability.  The issue should be mitigated now.  I unfortunately don't have write permissions to this repo, but I've put in a [PR ](https://github.com/PowerShell/PowerShellGallery/blob/eddb15751751b66fa5275d906459de5ce5ef2c0b/psgallery_status.md)to update the status.  Feel free to comment here with updates on whether builds are still breaking.  We're working on completely resolving the issue, but I'm hoping the scenario's improved for most.

_Originally posted by @alerickson in https://github.com/PowerShell/PowerShellGallery/issues/132#issuecomment-704875043_

**Comment by AnthonyGarriga** [comment]
Same issue here. Hopefully it will be fixed soon.

**Comment by mbrownphotouk** [comment]
Took longer to time out but still failed

**Comment by mbrownphotouk** [comment]
Took longer to time out but still failed

**Comment by mbrownphotouk** [comment]
Took longer to time out but still failed

**Comment by alphaleonis** [comment]
Yeah, still doesn't work here either.

**Comment by hallerx** [comment]
Still not working.

**Comment by ajithvs** [comment]
Same issue here..

**Comment by aperally** [comment]
same here (Ireland)

**Comment by jlbaptista** [comment]
Can confirm @aperally statement.
Continues to be down in Ireland.

**Comment by mbrownphotouk** [comment]
@alerickson Any update?

**Comment by Jezour** [comment]
> Hi all, we currently have an outage and are working on resolving it. Our CDN is down preventing packages from being downloaded and availability for the gallery itself has been extremely low. I'll update here as mitigation steps progress.

Can you please update the https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md ?

**Comment by harisubramaniam1** [comment]
Same here UK

**Comment by gokusupa** [comment]
Large impact here.

**Comment by LeoSchoonhoven** [comment]
Same here, pulling out my hairs as to why it wasn's working

**Comment by jogendrajangid1** [comment]
Created a pull request to update the status page - https://github.com/PowerShell/PowerShellGallery/pull/136

**Comment by DanielFrei64** [comment]
it JUST came up for me.. hopefully long enough to get a couple pipelines through

**Comment by venkat1017** [comment]
Still not for me. I tried a few minutes back

**Comment by snd3r** [comment]
I had a problem with installing PSReadline, now I have a second one - I don't understand why so many people don't vendor their dependencies.

**Comment by MonaMoravej** [comment]
We (In Sitecore) still have the issue, any ETA on that? has been blocking us for hours.

**Comment by s1mark** [comment]
Unable to install azure related modules...

**Comment by providyn** [comment]
For me this means I am dead in the water to managing my WVD 1.0 environment because it is 100% managed by Powershell and I rebuilt my machine and cannot reinstall the modules needed to manage it.

**Comment by PaulVrugt** [comment]
It's been down for over 7 hours now....this is getting ridiculous

**Comment by andersidahl** [comment]
what is happening??? Still down.....

**Comment by gokusupa** [comment]
Anybody remember last year when Azure Devops went down in south central US and we all wondered why there was no redundancy of the Azure Devops systems in other datacenters. The entirety of their development platform was down for a day for the entire customer base.

Pepperidge farms remembers

**Comment by amorvillier** [comment]
Workaround to install Az module:
Az module could be installed from the last msi file: 
[https://github.com/Azure/azure-powershell/releases/download/v5.0.0-October2020/Az-Cmdlets-5.0.0.33612-x64.msi](Az-Cmdlets-5.0.0.33612-x64.msi)

**Comment by MattJeanes** [comment]
For those who just need Az modules and are using Azure Pipelines see this comment, negates the need to install them at all as they are already pre-installed on Azure Pipelines Hosted Agents: https://github.com/PowerShell/PowerShellGallery/issues/132#issuecomment-716863626

**Comment by ReddyStuff** [comment]
> For those who just need Az modules and are using Azure Pipelines see this comment, negates the need to install them at all as they are already pre-installed on Azure Pipelines Hosted Agents: [#132 (comment)](https://github.com/PowerShell/PowerShellGallery/issues/132#issuecomment-716863626)

we are experiencing the issue even in AzurePowershell task. 
![image](https://user-images.githubusercontent.com/6813618/97712547-9800ff80-1ae4-11eb-817e-43bdbd27de36.png)

![image](https://user-images.githubusercontent.com/6813618/97712581-a2bb9480-1ae4-11eb-99d8-346348d491c8.png)


Inline Scripts to test:

Script 1 : Get-PSRepository

Script 2: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

**Comment by MattJeanes** [comment]
> we are experiencing the issue even in AzurePowershell task.

Personally we are using Azure CLI task set to Powershell Core and we use this bit of code to authenticate Az module from the CLI as we use both Az and CLI in our scripts.

```powershell
function Connect-AzAccountFromCli {
    Write-Debug "Connecting Az powershell account from cli"
    $token = (az account get-access-token) | ConvertFrom-Json
    $null = Connect-AzAccount -AccessToken $token.accessToken -AccountId $token.subscription -Tenant $token.tenant
}
```

Note if you do this the token will only last an hour or so and you will have to call that function again

**Comment by mbrownphotouk** [comment]
Doesnt help us that needs modules that are not azure based

**Comment by MattJeanes** [comment]
For other modules if you have them downloaded locally on your dev PC you could ship them with your code and do a local import, I've just changed our deployment scripts to do this with Newtonsoft.Json to eliminate our dependency on Powershell Gallery.

For example, I copied `C:\Users\<user>\Documents\Powershell\Modules\newtonsoft.json\1.0.2.201` (location varies depending on PowerShell version and install scope) into the same folder as our deployment scripts, renamed it to `Newtonsoft.Json` and then in our script ran `Import-Module -Name (Join-Path $PSScriptRoot "Newtonsoft.Json")`

You can see what modules are pre-installed on Azure Pipeline agents if you use those here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by Seclol** [comment]
Jesus, how is this still not fixed?

**Comment by codaamok** [comment]
Because it's probably a hard problem

**Comment by KingAlison** [comment]
I can't download EXO V2 powershell module from PSGallery.

**Comment by buckthebug** [comment]
> Because it's probably a hard problem

It seems they don't have any DR plan. 🤦‍♂️

**Comment by codaamok** [comment]
> > Because it's probably a hard problem
> 
> It seems they don't have any DR plan. 🤦‍♂️

Nor do you it seems!

**Comment by mbrownphotouk** [comment]
I could recommend a company that provides DR Services 

Someones prob missed a ; from a line of code somewhere

**Comment by buckthebug** [comment]
> > > Because it's probably a hard problem
> > 
> > 
> > It seems they don't have any DR plan. 🤦‍♂️
> 
> Nor do you it seems!
> 
> FWIW it's a free service. You're absolutely able to host your own nuget repositories if you have production workloads dependent on pulling modules from repositories.

We switched on the local/cached sources. ;)

**Comment by aperally** [comment]
> FWIW it's a free service. You're absolutely able to host your own nuget repositories if you have production workloads dependent on pulling modules from repositories.
 yeah, too bad MS hosts its own module in there too, or maybe I'm wrong and you can tell me where I can find MiscrosoftTeams module elsewhere?

**Comment by praath** [comment]
Our business is being immediately impacted by this issue. We need to deploy.

**Comment by jbotorek** [comment]
> > FWIW it's a free service. You're absolutely able to host your own nuget repositories if you have production workloads dependent on pulling modules from repositories.
> 
> yeah, too bad MS hosts its own modules in there too, or maybe I'm wrong and you can tell me where I can find MiscrosoftTeams module elsewhere?

Very unfortunate timing, indeed...

Any idea, where to find the _MicrosoftPowerBIMgmt_   package instead of this central repository, please?

**Comment by atyourservers** [comment]
The PowerShell Gallery team is working on mitigating the issue, but it's unclear with what priority, and what the expected timelines are. @alerickson, can you please provide an update?

**Comment by Geoff-Lillis** [comment]
> > FWIW it's a free service. You're absolutely able to host your own nuget repositories if you have production workloads dependent on pulling modules from repositories.
> 
> yeah, too bad MS hosts its own modules in there too, or maybe I'm wrong and you can tell me where I can find MiscrosoftTeams module elsewhere?

https://psg-prod-eastus.azureedge.net/packages/microsoftteams.1.1.6.nupkg

**Comment by SydneyhSmith** [comment]
Thanks everyone, we have had engineers working through the night on the issue and have pulled in multiple other teams to an ongoing active investigation--as engineers are waking up this morning we are pulling as many resources as possible into resolving the issue....unfortunately because this is an ongoing investigation we do not have an ETA  (this is our top priority and we will resovle as quickly as possible)

**Comment by clarkie2014** [comment]
I've been trying to install the Get-WindowsAutopilotInfo script for 1 hour then realised the powershell gallery wasn't loading. Had 19 laptops setup to start building! Can't believe it!

Will try again tomorrow and go get some pizza for now .

**Comment by kyanha** [comment]
Closing to reopen, to rerun CI.

**Comment by kyanha** [comment]
Reopening to rerun CI.

**Comment by ojintoad** [comment]
https://twitter.com/Steve_MSFT/status/1322293576974282753 🤞

**Comment by Maraudingas** [comment]
Works in Europe! Tested it with SQLServer module

**Comment by SydneyhSmith** [comment]
Thanks, we recently re-deployed the service after some fixes...we are currently validating the changes before updating the incident as mitigated

**Comment by simonsabin** [comment]
It looks like it might be the index that is out of date. I can’t republish the newer version

**Comment by SydneyhSmith** [comment]
Thanks folks we have mitigated the outage-- please refer to https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md for more details, we will follow up with a post-mortem

**Comment by SydneyhSmith** [comment]
Going to close out this issue, please let us know if you are still experiencing any issues

**Comment by nodenks** [comment]
Hi Team,

I am getting that problem from yesterday evening. Do you have any updates?

PS C:\Program Files\PowerShell\7-preview> [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
PS C:\Program Files\PowerShell\7-preview> Install-Module -Name DataGateway
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
Install-Package: C:\program files\powershell\7-preview\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'DataGateway'. Try
     | Get-PSRepository to see all available registered module repositories.
