### ISSUE TITLE
Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by providyn** [PowerShell/PowerShellGallery#138]
https://www.powershellgallery.com/packages/Microsoft.RDInfra.RDPowershell/1.0.1.11

Cannot load this page.

**Comment by sigv** [comment]
This appears to be a duplicate of #135 which has more details on the status.

Furthermore [psgallery_status.md](https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md) can be seen to list _the PowerShell Gallery is currently: Experiencing an outage_.
