### ISSUE TITLE
Install-Module does not work

### ISSUE THREAD

**Issue by MatejFrnka** [PowerShell/PowerShellGallery#140]
powershell command Install-Module does not work

`WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'ExchangeOnlin
eManagement'. Try Get-PSRepository to see all available registered module repositories.`

**Comment by SydneyhSmith** [comment]
Closing as a duplicate
