### ISSUE TITLE
AWS Tools for Windows PowerShell 4.1.3.0 disappeared 

### ISSUE THREAD

**Issue by ganeshnj** [PowerShell/PowerShellGallery#143]
## Description 
AWS Tools for Windows PowerShell 4.1.3.0 has disappeared from PowerShell Gallery after https://github.com/PowerShell/PowerShellGallery/issues/135 issues was resolved.

We have tried to upload the same artifacts to PowerShell Gallery with the same version i.e. 4.1.3.0 but getting 500.

```
 Failed to publish module 'AWSPowerShell': 'dotnet cli failed to nuget push Pushing AWSPowerShell.4.1.3.nupkg to 'https://www.powershellgallery.com/api/v2/package/'...
    PUT https://www.powershellgallery.com/api/v2/package/
    InternalServerError https://www.powershellgallery.com/api/v2/package/ 12094ms
    PUT https://www.powershellgallery.com/api/v2/package/
    InternalServerError https://www.powershellgallery.com/api/v2/package/ 4969ms
    PUT https://www.powershellgallery.com/api/v2/package/
    InternalServerError https://www.powershellgallery.com/api/v2/package/ 6829ms
EXEC : error : Response status code does not indicate success: 500 (There is a conflict with the name and version of your package and another package. Please change your package's name or version and try again.).
```

Our assumption is that 4.1.3.0 artifacts are there in the system but they aren't [indexed](https://github.com/PowerShell/PowerShellGallery/issues/135#issuecomment-719824245).

We released 4.1.3.0 between Thu 29-Oct-2020 21:48 and Fri 30-Oct-2020 00:01 (UTC).

**Comment by ganeshnj** [comment]
@SydneyhSmith can we have an update here?

**Comment by anamnavi** [comment]
@ganeshnj This package was published during our outage, so we have the nupkg for it, but it didn't make it into our database and thus isn't indexed like you correctly thought. If you would like we could add it to our database or you could update to a later version for your package? We apologize for the inconvenience and confusion regarding this.

**Comment by ganeshnj** [comment]
We have released a newer version of AWS Tools for Windows PowerShell i.e. 4.1.4.0 as workaround. Also, we don't have customers asking for 4.1.3.0, so no action required from PowerShell Gallery side.
