### ISSUE TITLE
AzureAD modules: project site links 404

### ISSUE THREAD

**Issue by mtillman** [PowerShell/PowerShellGallery#147]
The project site links for the AzureAD modules are broken. 

Modules with broken links are:
https://www.powershellgallery.com/packages/AzureAD/2.0.2.128
https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.129 

The broken project site links on those pages should be fixed as follows:

For AzureAD -
Current: https://docs.microsoft.com/en-us/powershell/azuread/v2/azureactivedirectory
New: https://docs.microsoft.com/powershell/module/azuread/?view=azureadps-2.0 

For AzureAD Preview
Current: https://docs.microsoft.com/en-us/powershell/azuread/v2/azureactivedirectory
New: https://docs.microsoft.com/powershell/module/azuread/?view=azureadps-2.0-preview

**Comment by SydneyhSmith** [comment]
Thanks @mtillman, these links are controlled by the package owner so they will need to update these...going to close as external
