### ISSUE TITLE
Unable to publish modules (TLS issue?)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/PowerShellGallery#148]
I've tried from multiple computers where I've previously been able to Publish-Module no problem.   I'm getting this:

```powershell
>Publish-Module -Name MSGraphPSEssentials -NuGetApiKey '<my NuGetApiKey (tried regen., new, no dice)>'
Publish-PSArtifactUtility : Failed to publish module 'MSGraphPSEssentials': 'The underlying connection was closed: An
unexpected error occurred on a send.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1227 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility
```
I checked the status on this repo's main readme, but it shows an old date, and up.

**Comment by JeremyTBradshaw** [comment]
I was able to get this working just now.  While I had the same issue last night and earlier this morning, using both PowerShell 7.1.0 and Windows PowerShell 5.1, just now it finally worked using PowerShell 7.1.0.

I was prompted to install newer Nuget.exe:
```powershell
NuGet.exe is required to continue
This version of PowerShellGet requires minimum version '4.1.0' of NuGet.exe to publish an item to the NuGet-based
repositories. NuGet.exe must be available in 'C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\' or
'C:\Users\j\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet\', or under one of the paths specified in PATH
environment variable value. NuGet.exe can be downloaded from https://aka.ms/psget-nugetexe. For more information, see
https://aka.ms/installing-powershellget . Do you want PowerShellGet to install the latest version of NuGet.exe now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
```
I am 99% sure I did in fact try in PowerShell 7.1.0 earlier this morning and last night, however, considering that prompt, I'm questioning myself.  I'll just leave this issue open and you guys can feel free to close it.

**Comment by danjagnow** [comment]
I have observed this behavior, too.  I got much better information with verbose logging after installing PowerShell 7.1 than when running `Publish-Module` under PowerShell 5.1.

**Comment by lelloz0** [comment]
> ```powershell
> NuGet.exe is required to continue
> This version of PowerShellGet requires minimum version '4.1.0' of NuGet.exe to publish an item to the NuGet-based
> repositories. NuGet.exe must be available in 'C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\' or
> 'C:\Users\j\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet\', or under one of the paths specified in PATH
> environment variable value. NuGet.exe can be downloaded from https://aka.ms/psget-nugetexe. For more information, see
> https://aka.ms/installing-powershellget . Do you want PowerShellGet to install the latest version of NuGet.exe now?
> [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
> ```

So this message is half a lie: on PowerShell 5.1 you must place (if you can't get to the internet) nuget.exe under `C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\` to make it work. I tried `C:\Windows` which is a path specified in the PATH env var value but it didn't work.
