### ISSUE TITLE
Warning: https://www.powershellgallery.com/  Website certificate will expire on March 23!

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShellGallery#156]
Warning:
https://www.powershellgallery.com/  Website certificate will expire on March 23!

**Comment by kasini3000** [comment]
@joeyaiello  @SteveL-MSFT   have a look,thanks

**Comment by alerickson** [comment]
@kasini3000 thanks for bringing this to our attention!  We'll take care of this.

**Comment by kasini3000** [comment]
ok
