### ISSUE TITLE
Get-AzureADPolicy is not working on  2.0.2.134 (current version)

### ISSUE THREAD

**Issue by jrmdcdc** [PowerShell/PowerShellGallery#159]
Hi,

Im trying to execute Get-AzureADPolicy but im getting the following error:

```
PS C:\Windows\system32> Get-AzureADPolicy                                                                                                                                                      Get-AzureADPolicy : Error occurred while executing GetPolicies
Code: Request_InvalidRequestUrl
Message: Request url was invalid. The request should be like /tenantdomainname/Entity or /$metadata. Tenant domain name can be any of the verified, unverified domain names or context id.
InnerError:
  RequestId: a0dbcd2e-5c62-4278-a6ed-b08deee60a55
  DateTimeStamp: Tue, 06 Apr 2021 12:57:38 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADPolicy
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-AzureADPolicy], ApiException
+ FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetPolicy
    
```
    Can someone please take a look on this?  I found the same issue on the Microsoft Q&A page but it looks like it was already resolve. Please note that i'm using the current version  2.0.2.134 (current version)

**Comment by jrmdcdc** [comment]
`PS C:\Windows\system32> Get-AzureADPolicy                                                                                                                                                      Get-AzureADPolicy : Error occurred while executing GetPolicies
Code: Request_InvalidRequestUrl
Message: Request url was invalid. The request should be like /tenantdomainname/Entity or /$metadata. Tenant domain name can be any of the verified, unverified domain names or context id.
InnerError:
  RequestId: a0dbcd2e-5c62-4278-a6ed-b08deee60a55
  DateTimeStamp: Tue, 06 Apr 2021 12:57:38 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADPolicy
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetPolicy
    `

**Comment by SydneyhSmith** [comment]
Thanks @jrmdcdc this issue looks like it it happening with the AzureADPreview module, the best thing would to contact the owners of that module for support
