### ISSUE TITLE
No way to select a logo in GUI

### ISSUE THREAD

**Issue by RStadlmair** [PowerShell/PowerShellGallery#16]
After uploading a module, i couldnt find a way to change the logo in the GUI.

This is possible in the current PowerShell Gallery, and should be in the preview as well

Regards/R.

**Comment by JKeithB** [comment]
Good catch - the link to edit the metadata is missing from the new UI.

**Comment by JKeithB** [comment]
@RStadlmair note that as a temporary workaround you can change that info using PowerShellGallery.com, and the Preview site will be updated also.

**Comment by JKeithB** [comment]
After reviewing this internally against the changes in NuGet v3, we realized that the UI used to edit the metadata (including the LogoURI) is no longer available in the latest NuGet base implementation. The primary reason stems from how the new protocol works for find-package & metadata extraction, particularly when interacting with CDN. 
What this means is that going forward, modifying the existing will need to be done by republishing the item. 
It also means we must add support for modifying the title of an item in the item manifests / powershellget, which is not possible today.
