### ISSUE TITLE
Connect-ExchangeOnline (v 2.0.4) fail with certificate logon

### ISSUE THREAD

**Issue by PatrizioCG** [PowerShell/PowerShellGallery#160]
Hi, we made all the stuff to let ps connecting to EXO with certificate authenication.
the login was successfully on azuread signins logs, but the ps can't connect with "Access Denied" error

How can we try to found some log / solve the issue ?

thank you

**Comment by SydneyhSmith** [comment]
Thanks, @PatrizioCG you should contact the owner of this cmdlet/module to get support
