### ISSUE TITLE
Slowness finding modules by name or loading module pages on PowerShell Gallery

### ISSUE THREAD

**Issue by boblodgett** [PowerShell/PowerShellGallery#175]
PowerShell Gallery has been operating slowly for the last couple of hours while trying to find-module or accessing modules on the PowerShell Gallery website. 

For example, it is taking between 12 and 84 seconds to load this page: https://www.powershellgallery.com/packages/AWSPowerShell

Find-Module AWSPowerShell is taking 20+ seconds to return.

Not every request is extremely slow.

**Comment by SteveL-MSFT** [comment]
We're looking into this

**Comment by adityapatwardhan** [comment]
The slowness should be fixed now. Please re-activate the issue if you still see problems. 

Thanks for reporting!

```powershell
❯ Measure-Command { Find-Module AWSPowerShell  } | Select-Object -ExpandProperty totalseconds
2.4630264
```
