### ISSUE TITLE
Query regarding package ownership

### ISSUE THREAD

**Issue by rashil2000** [PowerShell/PowerShellGallery#179]
Hi!

I sent a mail to PSGallery support a month ago, and got no response. I had CC'd the mail to myself too, and I am pasting the mail verbatim here, hoping to get some resolution.

> **Email:** 
> susheel1234 (susheel1234@live.com)
> 
> **Reason:**
> Requesting ownership of package name &quot;winfetch&quot;
> 
> **Message:**
> Respected sir/madam,
> 
> I would like to request the ownership of the script name &quot;Winfetch&quot;, in favor of a continually updated, more informative and immensely customizable version found here https://github.com/kiedtl/winfetch
> 
> I&#39;m currently a maintainer of that repository and it would be really great if we could publish under the name &quot;Winfetch&quot;.
> 
> I have tried contacting the current maintainer of the winfetch script here on PSGallery (link https://www.powershellgallery.com/profiles/Yahhms) but to no avail; they seem to be inactive since more than 2 years. 
> 
> Thanking you,
> 
> Sincerely
>

**Comment by rashil2000** [comment]
Some additional context:
Our package versioning starts from 2.0.0, so it won't cause any conflicts as the last published version of winfetch on PSGallery (which was more than 2 years ago) is 1.0.0

**Comment by anamnavi** [comment]
Hi @rashil2000, thanks for reaching out and we're sorry we missed your email. We'll take a look at it and respond today. Thanks!

**Comment by rashil2000** [comment]
@anamnavi I still haven't received any communication.

**Comment by rashil2000** [comment]
@anamnavi Would you please reopen this issue and close it _after_ it has been resolved? 
Thanks!
