### ISSUE TITLE
Font odd for PowerShellGallery on Ubuntu/Mac with Chrome 

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGallery#18]
See Twitter post [here](https://twitter.com/felixfbecker/status/1040355321787686912)

Need to ensure consistent experience for Windows & non-Windows users.

**Comment by felixfbecker** [comment]
![image](https://user-images.githubusercontent.com/10532611/45518410-adeec180-b7b1-11e8-925a-f24b215464a2.png)

**Comment by SydneyhSmith** [comment]
As far as I can tell this issue has been fixed--Mac on chrome is displaying the correct font.
