### ISSUE TITLE
Can't login with microsoft account

### ISSUE THREAD

**Issue by gfody** [PowerShell/PowerShellGallery#181]
I'm getting this error message as I try to login:

We're unable to complete your request

unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by baristaTam** [comment]
We are also unable to sign in from my organization

**Comment by alerickson** [comment]
This issue should be resolved now (as of roughly 30 minutes ago).  I apologize for the confusion and inconvenience!
