### ISSUE TITLE
Error occurred while executing SetUserManager 

### ISSUE THREAD

**Issue by mifitous** [PowerShell/PowerShellGallery#182]
Using AzureAD.Standard.Preview , and then Connect-AzureAD
Running on macOS Big Sur version 11.5.1 (20G80)
MacBook Pro (13-inch, **M1**, 2020)

When running:
 Set-AzureADUserManager -ObjectId  f15ec168-cc01-4930-8498-5dd56bba2ddd -RefObjectId cc8f4cb0-6afb-41ff-91fb-5a6f84b1769e
Set-AzureADUserManager: Error occurred while executing SetUserManager 
Code: Request_BadRequest
Message: The URI 'https://graph.windows.net**//**cb7ac32d-cdab-4986-89ce-0c93ce122a47/directoryObjects/cc8f4cb0-6afb-41ff-91fb-5a6f84b1769e' is not valid since it is not based on 'https://graph.windows.net/cb7ac32d-cdab-4986-89ce-0c93ce122a47/'.
RequestId: c9fe433a-498a-4311-b252-3bc60fe5cecd
DateTimeStamp: Tue, 17 Aug 2021 20:08:11 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

I suspect the double / is the root cause. Can it be?

**Comment by anamnavi** [comment]
Hi @mifitous thanks for reaching out. You'll need to get in touch with the package owner since this is related to an issue from their end, via the Contact Owner form on the package's webpage on PSGallery.
