### ISSUE TITLE
Sign in with Microsoft broken

### ISSUE THREAD

**Issue by baristaTam** [PowerShell/PowerShellGallery#183]
Happens in Edge, Chrome, Firefox. Multiple users affected. 
Steps to reproduce:
•	Browse to powershellgallery.com
•	Click Sign In (top right)
•	Click Sign in with Microsoft
•	Sign in with your Microsoft account and password, get one of two errors below:

Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier '8dc29313-29fc-4049-9e83-4abc54578e26' was not found in the directory [our tenant ID]. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

----

We're unable to complete your request
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by alerickson** [comment]
This should be resolved now.  I apologize for the issues regarding this!
