### ISSUE TITLE
Powershell Gallery Service Unavailable

### ISSUE THREAD

**Issue by hcparr** [PowerShell/PowerShellGallery#184]
Cannot access gallery or download packages.  When going to powershellgallery.com I receive a 503 Service Unavailable error and when trying to download a package it fails saying it cannot find the specified module.

**Comment by ShaunH-Iress** [comment]
I am experiencing this as well.

**Comment by alerickson** [comment]
Thank you all, we're looking into this issue with extreme urgency.  There seems to be an extremely slow connection causing timeouts.  I will update our status page with this issue and reply here with more updates.

**Comment by pkoushik** [comment]
We are seeing this as well - will wait on an update!

**Comment by alerickson** [comment]
It looks like our cloud services have degraded, I'm currently trying a redeployment.

**Comment by crc56** [comment]
Are there any updates on this?

**Comment by roshangautam** [comment]
would appreciate any updates on this. This is blocking our release pipelines

**Comment by OzoneNZ** [comment]
Back up and running for me :)

**Comment by alerickson** [comment]
Should be back up and running as of about 20 minutes ago.  Instances were booting up slowly over this time but we are in near full capacity again.

**Comment by alerickson** [comment]
I’m closing this issue because the issue seems to be fully resolved now, after roughly 30 minutes of stable connectivity.  Of course please feel free to open up an issue or comment here if you’re still encountering this problem or experience latency.  I appreciate the patience as we slowly try to improve on the vast technical debt that exists in the Gallery.

**Comment by Doc94** [comment]
Hi, i dont know if is the same issue but when update a module get a error for "powershell gallery is currently unavailable"
![image](https://user-images.githubusercontent.com/3602279/129915675-b19e5511-3ed8-4d4c-af82-d4a887ee7985.png)
