### ISSUE TITLE
Register-PackageSource : Source Location 'https://www.powershellgallery.com/api/v2' is not valid.

### ISSUE THREAD

**Issue by stmoor** [PowerShell/PowerShellGallery#185]
I am trying to install a module and I get the following error:

![image](https://user-images.githubusercontent.com/77985069/129817621-869d55c4-7252-4658-8469-18ec0881fb6c.png)

After some googling, I found some solutions such as enforcing TLS12 by calling the following command
 
```PowerShell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
````

This did not work for me. Another solution was to register the package source with the following command:

```PowerShell
Register-PackageSource -Name PSNuGet -Location "https://www.powershellgallery.com/api/v2" -ProviderName NuGet
```

But I get the following error too , which I think is related to the previous:
![image](https://user-images.githubusercontent.com/77985069/129817762-878ffd99-50f4-43ee-82f4-9eb6585e502a.png)

Please advise.

**Comment by okazakov** [comment]
Yep, https://www.powershellgallery.com/api/v2 is completely down.
Requests are timing out.
Is it expired TLS cert again?
C'mon Microsoft! We can no longer rely on your services anymore. The frequency with which PSGallery is unavailable is embarrassing.  Get your act together already.

**Comment by alerickson** [comment]
This issue is resolved now
