### ISSUE TITLE
PowershellGallery.com Cert has expired

### ISSUE THREAD

**Issue by Sunitakumari** [PowerShell/PowerShellGallery#186]
It seems that the certificate for powershell gallery (https://www.powershellgallery.com/) has expired.
I can't seem to download any modules from the gallery now.

Error:
The term 'Add-AzureAnalysisServicesAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by alerickson** [comment]
Hello, we had an availability issue due to a deleted AAD app registration.  This issue is resolved now.  Please see our status file for more details.  Thank you and we apologize for this extreme inconvenience!
