### ISSUE TITLE
Full stats UI looks odd if only 1 version of package

### ISSUE THREAD

**Issue by JKeithB** [PowerShell/PowerShellGallery#19]
Find a package with only 1 version, I used [psnodejsmanager](https://www.powershellgallery.com/packages/PSNodeJSManager/). 
In the left nav, select "View Full Stats"
The UI looks very strange with a single bar taking the whole graph . 
Would be better if the bar had a max width

**Comment by edyoung** [comment]
True, but it is unlikely we will look at this any time soon.
