### ISSUE TITLE
Unable to Contact Package Owner

### ISSUE THREAD

**Issue by joshcampbell191** [PowerShell/PowerShellGallery#191]
Sorry if this isn't the right place for this. I've tried reaching out via the contact form but haven't received a response. 

It's not currently possible to submit the Contact Owners form due to a configuration issue with reCaptcha. 

![image](https://user-images.githubusercontent.com/1784236/133330109-96d6593a-36a6-4bdc-9256-24733e5ad6cc.png)

**Comment by StevenBucher98** [comment]
Thank you @joshcampbell191, we are working on updating our deployment pipelines and hope to have it fixed by the end of the month.

**Comment by alerickson** [comment]
This issue is resolved now
