### ISSUE TITLE
PowerShell Gallery Update Sept 22, 2021: Publish Impact?

### ISSUE THREAD

**Issue by ppittle** [PowerShell/PowerShellGallery#193]
There's a status update on https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md:

> From Monday, September 27th to Thursday, September 30th a migration will occur to a new (ARM based) cloud service. We do not anticipate that this will interrupt traffic or interfer with Gallery access.

**Will this impact Publishing modules?**

I'm looking to publish a few hundred modules updates, will it be safe to do during the week of this migration?  Is there any point of the window that might be best to avoid publishing?

**Comment by alerickson** [comment]
Hi @ppittle,  feel free to publish any time.  The migration process required creating some more resources than we expected so this will likely continue on through next (I'll update our status and banner to reflect this shortly).  Publishing at any point will be safe, and if for any reason we suspect that it would not be I will immediately update our website banner and status markdown here to explicitly state that.

**Comment by ppittle** [comment]
Sounds good, thanks for the clarification!
