### ISSUE TITLE
unable to install-module  AWS.Tools.IdentityManagement

### ISSUE THREAD

**Issue by Saratoga6** [PowerShell/PowerShellGallery#195]
I am running Name  PSVersion      5.1.14393.4583     on win 2012 std edi. Al other module install /import fine
when I try install 
 **Install-Module -Name AWS.Tools.IdentityManagement**
Returns
PackageManagement\Install-Package : Authenticode issuer 'CN="Amazon Web Services, Inc.", OU=SDKs and Tools, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US, SERIALNUMBER=4152954, 
OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US, OID.2.5.4.15=Private Organization' of the new module 'AWS.Tools.Common' with version '4.1.15.0' from root certificate authority 'CN=DigiCert Trusted Root 
G4, OU=www.digicert.com, O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN="Amazon Web Services, Inc.", OU=AWS, O="Amazon Web Services, Inc.", L=Seattle, S=Washington, C=US' of the previously-installed 
module 'AWS.Tools.Common' with version '4.1.14.0' from root certificate authority 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. If you still want to install or update, use -SkipPublisherCheck 
parameter.
At C:\Users\xxxxx\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : AuthenticodeIssuerMismatch,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
any help here?  doe snot seem  problem I can resolve locally  . yes?   I already  tried to update the Install-module.    

Why is the  AWS.Tools  set  plagude with  these  types of issues?

**Comment by klementi** [comment]
This issue is announced/explained here https://github.com/aws/aws-tools-for-powershell/issues/232, sorry for the inconvenience
