### ISSUE TITLE
Re: Query regarding package ownership

### ISSUE THREAD

**Issue by rashil2000** [PowerShell/PowerShellGallery#201]
Hi!

I sent a mail to PSGallery support 4 months ago, and got no response. I had CC'd the mail to myself too, and I am pasting the mail verbatim here, hoping to get some resolution.

> **Email:**
> susheel1234 ([susheel1234@live.com](mailto:susheel1234@live.com))
> **Reason:**
> Requesting ownership of package name "winfetch"
> **Message:**
> Respected sir/madam,
> I would like to request the ownership of the script name "Winfetch", in favor of a continually updated, more informative and immensely customizable version found here https://github.com/kiedtl/winfetch
> I'm currently a maintainer of that repository and it would be really great if we could publish under the name "Winfetch".
> I have tried contacting the current maintainer of the winfetch script here on PSGallery (link https://www.powershellgallery.com/profiles/Yahhms) but to no avail; they seem to be inactive since more than 2 years.
> Thanking you,
> Sincerely

I previously opened an issue here to get help - #179, but it was closed without and before any response.

**Comment by SydneyhSmith** [comment]
Thanks @rashil2000 we will need permission from a current package owner in order to make the change...apologies for closing out your previous issue before this was resolved.

**Comment by rashil2000** [comment]
Thank you for the reply @SydneyhSmith 


Some additional context (pasting from #179):
Our package versioning starts from 2.0.0, so it won't cause any conflicts as the last published (by Yahhms) version of winfetch script on PSGallery (which was more than 2 years ago) is 1.0.0

I would like to ask one thing: what is the period for which you wait till the original package owner responds? (they might not be active on PSGallery anymore as I had mailed them too, and got no response).

**Comment by alerickson** [comment]
Hi @rashil2000 I just wanted to give you a quick update, we'll have an answer for you as to how we can best address this situation by the end of the week.  Thank you so much for your patience, we hope to get this resolved very soon.

**Comment by rashil2000** [comment]
Alright, thanks for the heads up!

**Comment by rashil2000** [comment]
Hey @alerickson, just checking in to see any updates on this. It's been another month...

**Comment by anamnavi** [comment]
Closing this as it was resolved via email. If you have any issues please feel free to reach out, thanks!

**Comment by rashil2000** [comment]
Thanks so much! Issue resolved :)
