### ISSUE TITLE
PowerShell Gallery is currently unavailable.  Please try again later.

### ISSUE THREAD

**Issue by coryburdit** [PowerShell/PowerShellGallery#205]
Currently getting the below when trying to run Update-Module.

Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2038 char:13
+             Get-PSGalleryApiAvailability -Repository (Get-SourceName  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability

Have forced TLS 1.2 via PowerShell but still have this issue.

**Comment by SBALA4785** [comment]
I have fixed mine with below ref,

https://dev.to/darksmile92/powershell-disabled-support-for-tls-1-0-for-the-gallery-update-module-and-install-module-broken-1oii

**Comment by robinmalik** [comment]
Is anyone at Microsoft reviewing these issues? Why would there be an open issue from November 2021, 5 months ago, referencing a temporary unavailability issue? (there have been many others of the same problem, since then)!

**Comment by coryburdit** [comment]
Let's just say I got it fixed but don't remember what I did to fix it. I don't know if anyone at Microsoft is looking t these issues.
