### ISSUE TITLE
api that is used in kbupdate 1.0.12 is dead

### ISSUE THREAD

**Issue by wagde-orca** [PowerShell/PowerShellGallery#207]
in the https://www.powershellgallery.com/packages/kbupdate/1.0.12/Content/public%5CGet-KbUpdate.ps1 there is access to "https://support.microsoft.com/app/content/api/content/help/en-us/$kb"
and it seems microsoft moved/removed this api.

**Comment by o-l-a-v** [comment]
How is that a PowerShellGallery issue? It's probably better to ask the module author instead, "Chrissy LeMaire".

* https://www.powershellgallery.com/packages/kbupdate/1.1.22/ContactOwners

**Comment by fflaten** [comment]
It's also fixed in newer versions of the module, so ready to close @wagde-orca or @SydneyhSmith. 🙂
