### ISSUE TITLE
Can't request JSON response with API calls to /api/v2

### ISSUE THREAD

**Issue by chris48s** [PowerShell/PowerShellGallery#21]
Hi. We rely on the powershell gallery API on https://shields.io/ to generate badges which are used by many popular powershell gallery projects. Since the recent updates to powershell gallery, we are now unable to request data from the API in JSON format - it seems the content negotiation header is no longer respected. For example, if I call

```
$ curl -H "Accept: application/atom+json,application/json" "https://www.powershellgallery.com/api/v2/Packages()?$filter=Id%20eq%20'ACMESharp'%20and%20IsLatestVersion%20eq%20true"
```

this now unexpectedly returns an XML response. This means none of our powershell gallery badges will render because the code that generates them expects JSON and fails to parse the XML response. Examples:

* https://github.com/Azure/azure-powershell#modules
* https://github.com/Microsoft/powerbi-powershell#powershell-modules
* https://github.com/Microsoft/vssetup.powershell#visual-studio-setup-powershell-module

Do we now need to pass a different header, or is this a bug?  It would be great if we could get these fixed for our mutual users.

**Comment by JKeithB** [comment]
Sorry for the issue, Chris48s, we are working on it.
That problem is the core of the issue which broke our connection to the Automation Gallery (see https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md#powershell-gallery-status) 
We don't have an ETA yet, but it is something we are working to address.

**Comment by chris48s** [comment]
Thanks for responding @JKeithB :+1:  I'l check in on this next week

**Comment by edyoung** [comment]
@Chris48s, how much of a problem would it be for you to request and parse XML instead of JSON? Reason I ask is that all the primary clients of the PowerShell Gallery (like PowerShellGet) currently use XML so that gets a lot more testing and verification. cc @rebro-msft

**Comment by chris48s** [comment]
Hi @edyoung

We're a community-driven project and rely on contributions from volunteers. I'll give a quick summary of what would be involved:

At the moment we've got some shared code for parsing feeds from services which build on NuGet package manager/gallery. We've got a one for NuGet V2 currently shared by the integrations for PowerShell Gallery, Chocolatey and ReSharper Gallery and another one for NuGet V3 shared by the NuGet and MyGet badges. All of it assumes the response is JSON and everything other than PowerShell Gallery currently works, although the code is not so elegant. If we need to switch to XML for PowerShell Gallery, I'd be inclined to treat PowerShell as a special case at first rather than try to migrate mutliple services at once.

In order to do that, we'd need a `BasePowerShellGalleryService` class, which extends `BaseXmlService` and then 2 further classes `PowerShellGalleryDownloads` (for the downloads badge) and `PowerShellGalleryVersion` (for the version badge) each extending `BasePowerShellGalleryService`. The closest badge family to crib from as an example would be the [eclipse marketplace badges](https://github.com/badges/shields/tree/master/services/eclipse-marketplace). We use [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) for XML processing. We do have at least have a good [test suite](https://github.com/badges/shields/blob/master/services/powershellgallery/powershellgallery.tester.js) for PowerShell Gallery, which would make things easier.

If you are interested in submitting a pull request to help us switch us to the XML API, feel free to follow up and ask more questions - we're happy to work with new contributors. Cheers.

**Comment by mithrandyr** [comment]
Any update on this issue? been over 2 weeks -- all my PowerShell Module repos (on GitHub) rely on the Shields.io service and I really would like for the badges to start working again.  Also, some of MS own repos on GitHub also rely on this service and their shields aren't working either (showing "invalid") -- https://github.com/Azure/azure-powershell

**Comment by chris48s** [comment]
Just as an update on this, we've switched our code to use the XML outputs so this no longer affects us. It is possible there may be other users affected by this issue. Happy if you want to close the issue.

**Comment by edyoung** [comment]
Hi Chris, sorry we broke the json version of this API, and really appreciate the work you've done to update shields.io.

**Comment by JustinGrote** [comment]
For anyone coming to this, to close the loop, the json was never fixed, and XML is still the only option, at least as far as I can tell.
