### ISSUE TITLE
Powershell test environment offline?

### ISSUE THREAD

**Issue by soloji** [PowerShell/PowerShellGallery#219]
I am unable to reach the test powershell gallery, I am located South East Australia

Is this an expected outage or permanent decommissioning of the  test environment? I use it because it has the Linux AzureAD modules available that I use in my pipelines. 
We are working to migrate to MsGraph but still need need that preview package.

I have tried navigating to  https://www.poshtestgallery.com with a timeout and down detector also reports it offline

Any info or if others are having this issues would be good to know.

```
Write-Output "Installing AzureAD Powershell Module"
    Write-Warning "Azure AD Powershell is deprecated from June 2022, use Connect-CurrentUserToMsGraph and the Microsoft Graph SDK Powershell module instead"
    if ($PSversionTable.OS -match ".*Linux.*") {
        Register-PackageSource -Trusted -ProviderName 'PowerShellGet' -Name 'Posh Test Gallery' -Location 'https://www.poshtestgallery.com/api/v2/' -Force
        Install-Module -Name 'AzureAD.Standard.Preview' -RequiredVersion 0.0.0.10 -Force -Scope CurrentUser -SkipPublisherCheck -AllowClobber 
        Import-Module AzureAD.Standard.Preview
```

**Comment by alerickson** [comment]
Hello all, we are aware that the test site is down.  Just as a note, poshtestgallery.com is a test site for the Gallery, not for packages or users.  This is where we test changes and experiment before deploying to powershellgallery.com. This website and the packages on this site are not meant for production.  We have a banner on poshtestgallery to explain this, but unfortunately sometimes package owners still publish there.  What are the full names of the modules you need?  Are they available on powershellgallery.com?  If not, I can reach out to the module owners and see if they would be willing to publish there.  We're working on getting poshtest back up, but to prevent this from happening again in the future let's see if we can get all modules into the powershellgallery.  cc: @anamnavi  @SydneyhSmith @StevenBucher98

**Comment by soloji** [comment]
An AzureAD module that works fully on Linux is a long running issue and this module has been the only module that has all the features that Linux users require, it sadly isn't available on the main production powershell site.

if this package was in the production gallery I would move off the test environment immediately.  

https://web.archive.org/web/20201128130803/https://www.poshtestgallery.com/packages/AzureAD.Standard.Preview/0.0.0.10

I appreciate the update

**Comment by SeidChr** [comment]
As i needed the module myself, i have extracted it from the azure cloud shell.
Hope it doesn't break any rules to post this here.
If so, feel free to remove the file.
[azureadcore.zip](https://github.com/PowerShell/PowerShellGallery/files/8286263/azureadcore.zip)

To obtain it yourself, use the following commands in your cloud-shell:
```ps
Copy-Item -Path "/usr/local/share/powershell/Modules/AzureAD.Standard.Preview" -Recurse -Destination ./azadcore/
CD ./azadcore
Compress-Archive ./AzureAD.Standard.Preview/ ../clouddrive/azureadcore
```
note that the destination should be in your clouddrive folder, so you can find the file in the files-share of your cloudshell storage account

**Comment by jeff-simeon** [comment]
> Hello all, we are aware that the test site is down. Just as a note, poshtestgallery.com is a test site for the Gallery, not for packages or users. This is where we test changes and experiment before deploying to powershellgallery.com. This website and the packages on this site are not meant for production. We have a banner on poshtestgallery to explain this, but unfortunately sometimes package owners still publish there. What are the full names of the modules you need? Are they available on powershellgallery.com? If not, I can reach out to the module owners and see if they would be willing to publish there. We're working on getting poshtest back up, but to prevent this from happening again in the future let's see if we can get all modules into the powershellgallery. cc: @anamnavi @SydneyhSmith @StevenBucher98

AzureAD.Standard.Preview is used by tens of thousands of users in production (including by Microsoft itself) and this is the only place to install it from

**Comment by egraff** [comment]
[This comment](https://github.com/PowerShell/PowerShell/issues/17019#issuecomment-1079483836) states that:
> The test gallery actually becomes Microsoft internal access only, due to a policy enforced in Microsoft. The gallery team intends to keep it internal accessible only [...]

If that is the case, then Microsoft really should make the AzureAD.Standard.Preview module available elsewhere.

**Comment by balmer40** [comment]
Is there anywhere else we can get AzureAD.Standard.Preview module from? The test site is still down

**Comment by anamnavi** [comment]
We'll reach out to the AzureAD.Standard.Preview module owners and ask them to publish it to powershellgallery.com.

**Comment by SydneyhSmith** [comment]
Unfortunately the original module owners are not interested in owning/supporting this module on the Gallery, with the guidance of using Graph...I can imagine that is frustrating for folks who need the module...I did see that someone published the zip above for use
