### ISSUE TITLE
PowerShell Gallery is currently unavailable - AGAIN

### ISSUE THREAD

**Issue by sameer-kumar** [PowerShell/PowerShellGallery#223]
Our Azure DevOps pipelines are failing while installing modules from POSH gallery. This all started this morning 04/05/22.

Here is the error from pipeline task:
`System.Management.Automation.RuntimeException: PowerShell Gallery is currently unavailable. Please try again later.`

TLS1.2 is already configured in the task:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Ssl3, [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls12`

This is the command which fails:
`Install-Module -Name cNtfsAccessControl -RequiredVersion $requiredVersion -Repository 'PSGallery' `
 
Is it just us?

**Comment by SydneyhSmith** [comment]
Thanks for opening this issue @sameer-kumar our monitoring didnt indicate an outage at this time, although we are doing more investigation, are you still experiencing this issue?

**Comment by sameer-kumar** [comment]
Its disappeared now. Nothing changed in our pipelines. I don't know what was the issue.

**Comment by sameer-kumar** [comment]
Its happening again. Last error noted on 04/14/22. Following failed attempts:
1. 6:15 pm
2. 6:30 pm
3. 7:25 pm
*All times are in eastern time zone.*

**Comment by SydneyhSmith** [comment]
Thanks for the info, wanted to update you that this is not showing in our monitoring so we are investigating what could be happening

**Comment by jbolduan** [comment]
It appears to be offline hard right now, website is down and unable to publish a module using our Azure DevOps pipeline.

**Comment by SydneyhSmith** [comment]
Thanks, we are investigating the issue and working to get the gallery up as quickly as possible...will try to post updates as available

**Comment by SydneyhSmith** [comment]
This is now resolved, please let us know if you are still experiencing any issues

**Comment by Angel-CDO** [comment]
Still experiencing the issue (from several locations)
![image](https://user-images.githubusercontent.com/94907066/173684265-b5a2cc8b-4485-41a5-bd02-d439db14111d.png)

**Comment by GunArm** [comment]
I am also still experiencing the issue.  It has not changed since the psgallery_status.md was updated to save resolved.  I get exactly the same output as @Angel-CDO above (no need to repaste it).  I get this result both from PCs on my network as well as from EC2s exiting aws.

**Comment by GunArm** [comment]
Yes I am, and before it was "resolved" I was not able to.  So that did change.

```
PS C:\WINDOWS\system32> curl www.powershellgallery.com | head


StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html>
                    <html lang="en">
                    <head>
                        <meta charset="utf-8" />
                        <meta http-equiv="X-UA-Compatible" content="IE=edge">
                        <meta name="viewport" content="width=device-width, initial-scale...
PS C:\WINDOWS\system32> Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4302 char:9
+         Get-PSGalleryApiAvailability -Repository $Name
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability

PS C:\WINDOWS\system32> Find-Module -Name PSReadLine -Repository PSGallery |Get-Member
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1342 char:9
+         Get-PSGalleryApiAvailability -Repository $Repository
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability

Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4475 char:9
+         Get-PSGalleryApiAvailability -Repository $Name
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability

Get-Member : You must specify an object for the Get-Member cmdlet.
At line:1 char:53
+ Find-Module -Name PSReadLine -Repository PSGallery |Get-Member
+                                                     ~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
```

**Comment by mzarglis** [comment]
Still down for me ( east coast NA)

**Comment by GunArm** [comment]
To add:  After getting home from work I tried running it on my home computer, and it succeeds.  I remoted back into work and it still fails both from my work and from an EC2 with no outgoing firewall rules.  As mentioned above I ran `ipconfig /flushdns`, however I only know enough about DNS to know it's layered and incomprehensible.  Maybe some kind of propagation issue, although I can access the site in a browser...?

**Comment by mzarglis** [comment]
For the packages there is probably multiple regional CDNs which why it may work from some places and not others as DNS propogates and caches timeout

**Comment by mzarglis** [comment]
@GunArm 

For the packages there is probably multiple regional CDNs which why it may work from some places and not others as DNS propogates and caches timeout

**Comment by SydneyhSmith** [comment]
Checking back in-- anyone still experiencing issues downloading from the site?

**Comment by mzarglis** [comment]
@SydneyhSmith  Resolved for me. Thanks!

**Comment by RZABob** [comment]
Running into this now. Common workarounds haven't resolved it. Just me?
