### ISSUE TITLE
 # Get the hash (if available)   issue getting hash file from Dynabook A40

### ISSUE THREAD

**Issue by adjackouk** [PowerShell/PowerShellGallery#228]
I have 20 Dynabook A40's, 18 of them have retrieved the hash file with no issues, 2 of them give me the below error when running 
 
****_$devDetail = (Get-CimInstance -CimSession $session -Namespace root/cimv2/mdm/dmmap -Class MDM_DevDetail_Ext01 -Filter "InstanceID='Ext' AND ParentID='./DevDetail'")_****

I get this message on the devices ;

**_Get-CimInstance : A general error occurred that is not covered by a more specific error code.
At D:\Autopilot\Get-WindowsAutoPilotInfo.ps1:209 char:23
+ ... evDetail = (Get-CimInstance -CimSession $session -Namespace root/cimv ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand_**

The operating system is Windows 10 Pro 21H2, any advice would be greatly appreciated.

Thank you.

**Comment by Robert-Azelis** [comment]
It looks on global problem for Windows 10 registration via Autopilot, after install **KB5013942 - 2022-05 Cumulative Update for Windows 10 Version 21H2**.
At this moment, only on solution is uninstall this KB via command **wusa.exe /uninstall /KB:5013942**.
If device is enrolled (registered in Intune) then you can update device.

For Windows 11 problem doesn't exist, even if KB 2022-05 is installed!

**Comment by NOLA-StsFan** [comment]
@Robert-Azelis -
Removing **KB5013942**, **Security Update for Microsoft**, worked for me.  Another post referenced KB5011831 but it wasn't installed.  Thanks!

**Comment by Robert-Azelis** [comment]
> It looks on global problem for Windows 10 registration via Autopilot, after install **KB5013942 - 2022-05 Cumulative Update for Windows 10 Version 21H2**. At this moment, only one solution is uninstall this KB via command **wusa.exe /uninstall /KB:5013942**. If device is enrolled (registered in Intune) then you can update device.
> 
> For Windows 11 problem doesn't exist, even if KB 2022-05 is installed!

I just tested new **KB5014699 2022-06 Cumulative Update for Windows 10 Version 21H2 for x64** on fresh installed system Windows 10 21H2, **NO issue so far**, script is able gathering hash data device from MDM_DevDetail_Ext01 class.

Let us know if it works for you.
