### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by SleepTheGod** [PowerShell/PowerShellGallery#229]
Lin : https://www.powershellgallery.com/Errors/500?aspxerrorpath=/%3Cscript%3Ealert(%22SleepTheGod%22);%3C/script%3E
Below is the view-source: of the above page
`<html>
<body>

<!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta charset="utf-8" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  |  
  |  
  |  
  | <title>
  | PowerShell Gallery
  | \| Internal Server Error
  | </title>
  |  
  | <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  | <link title="https://www.powershellgallery.com" type="application/opensearchdescription+xml" href="/opensearch.xml" rel="search">
  |  
  | <link href="/Content/gallery/css/site.min.css?v=PiyChSWpJyC8Kpz_ZV5FuONZ0GHHOfH16uZN51B4pbI1" rel="stylesheet"/>
  |  
  | <link href="/Content/gallery/css/branding.css?v=1.2" rel="stylesheet"/>
  |  
  |  
  |  
  | 
  | 
  | 
  |  
  |  
  |  
  |  
  |  
  |  
  | 
  | <script type="text/javascript">
  | var appInsights = window.appInsights \|\| function (config) {
  | function s(config) {
  | t[config] = function () {
  | var i = arguments;
  | t.queue.push(function () { t[config].apply(t, i) })
  | }
  | }
  |  
  | var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u;
  | for (o.src = config.url \|\| "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) s("track" + i.pop());
  | return config.disableExceptionTracking \|\| (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) {
  | var s = u && u(config, r, f, e, o);
  | return s !== !0 && t["_" + i](config, r, f, e, o), s
  | }), t
  | }({
  | instrumentationKey: '50d4abc3-17d3-4a1b-8361-2d1e9ca8f6d5',
  | samplingPercentage: 100
  | });
  |  
  | window.appInsights = appInsights;
  | appInsights.trackPageView();
  | </script>
  |  
  | </head>
  | <body role="presentation">
  |  
  |  
  |  
  |  
  |  
  |  
  | <nav class="navbar navbar-inverse" role="navigation">
  | <div class="container">
  | <div class="row">
  | <div class="col-sm-12 text-center">
  | <a href="#" id="skipToContent" class="showOnFocus" title="Skip To Content">Skip To Content</a>
  | </div>
  | </div>
  | <div class="row">
  | <div class="col-sm-offset-1 col-sm-2">
  | <div class="navbar-header">
  | <a href="/" class="nvabar-header-aLink">
  | <img class="navbar-logo img-responsive" alt="PowerShell Gallery Home"
  | src="/Content/Images/Branding/psgallerylogo.svg"
  | onerror="this.src='https://powershellgallery.com/Content/Images/Branding/psgallerylogo.png'; this.onerror = null;"
  | />
  | </a>
  | <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" title="Open Main Menu and profile dropdown">
  | <span class="sr-only">Toggle navigation</span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | <span class="icon-bar"></span>
  | </button>
  | </div>
  | </div>
  | <div class="col-sm-12 col-md-8 special-margin-left">
  | <div id="navbar" class="navbar-collapse collapse" role="navigation" aria-label="Navigation Bar">
  | <table role="presentation">
  | <tr>
  | <td colspan="3">
  | <ul class="nav navbar-nav" role="tablist">
  | <li class="" role="presentation">
  | <a role="tab" aria-selected="false" href="/packages" target="" aria-label="Packages">
  | <span aria-hidden="true">Packages</span>
  | </a>
  | </li>
  |  
  | <li class="" role="presentation">
  | <a role="tab" aria-selected="false" href="/packages/manage/upload" target="" aria-label="Publish">
  | <span aria-hidden="true">Publish</span>
  | </a>
  | </li>
  |  
  | <li class="" role="presentation">
  | <a role="tab" aria-selected="false" href="/stats" target="" aria-label="Statistics">
  | <span aria-hidden="true">Statistics</span>
  | </a>
  | </li>
  | <li class="" role="presentation">
  | <a role="tab" aria-selected="false" href="https://go.microsoft.com/fwlink/?LinkID=825202&amp;clcid=0x409" target="_blank" aria-label="Documentation">
  | <span aria-hidden="true">Documentation</span>
  | </a>
  | </li>
  |  
  | </ul>
  | </td>
  | <td colspan="1" class="td-align-topright">
  | <ul class="nav navbar-nav navbar-right" role="tablist">
  | <li class="" role="presentation">
  | <a role="tab" aria-selected="false" href="/users/account/LogOn?returnUrl=%2FErrors%2F500%3Faspxerrorpath%3D%2F%253Cscript%253Ealert%28%2522SleepTheGod%2522%29%3B%253C%2Fscript%253E" target="" aria-label="Sign in">
  | <span aria-hidden="true">Sign in</span>
  | </a>
  | </li>
  | </ul>
  | </td>
  | </tr>
  | </table>
  | </div>
  | </div>
  | </div>
  | </div>
  |  
  | <div class="container-fluid search-container">
  | <div class="row" id="search-row">
  | <form aria-label="Package search bar" action="/packages" method="get">
  | <div class="container">
  | <div class="row">
  | <div class="col-sm-offset-1 col-sm-2"></div>
  | <div class="col-sm-12 col-md-8">
  | <div class="form-group special-margin-left">
  | <label for="search">Search PowerShell packages:</label>
  | <div class="input-group"  role="presentation">
  | <input name="q" type="text" class="form-control ms-borderColor-blue search-box" id="search" aria-label="Enter packages to search, use the arrow keys to autofill."
  | placeholder="PowerShellGet, Get-AzVM, etc..." autocomplete="on"
  | value=""
  | />
  | <span class="input-group-btn">
  | <button class="btn btn-default btn-search ms-borderColor-blue ms-borderColor-blue--hover" type="submit"
  | title="Search PowerShell packages" aria-label="Search PowerShell packages">
  | <span class="ms-Icon ms-Icon--Search" aria-hidden="true"></span>
  | </button>
  | </span>
  | </div>
  |  
  | <div id="autocomplete-results-container" class="text-left" tabindex="0"></div>
  |  
  | <script type="text/html" id="autocomplete-results-row">
  | 
  | 
  | <div class="col-sm-4 autocomplete-row-id autocomplete-row-data">
  | <span data-bind="attr: { id: 'autocomplete-result-id-' + $data.PackageRegistration.Id, title: $data.PackageRegistration.Id }, text: $data.PackageRegistration.Id"></span>
  | </div>
  | <div class="col-sm-4 autocomplete-row-downloadcount text-right autocomplete-row-data">
  | <span data-bind="text: $data.DownloadCount + ' downloads'"></span>
  | </div>
  | <div class="col-sm-4 autocomplete-row-owners text-left autocomplete-row-data">
  | <span data-bind="text: $data.OwnersString + ' '"></span>
  | </div>
  | 
  | 
  | <div class="col-sm-12 autocomplete-row-id autocomplete-row-data">
  | <span data-bind="attr: { id: 'autocomplete-result-id-' + $data, title: $data  }, text: $data"></span>
  | </div>
  | 
  | 
  | </script>
  |  
  | <script type="text/html" id="autocomplete-results-template">
  | 
  | <div data-bind="foreach: $data.data" id="autocomplete-results-list">
  | <a data-bind="attr: { id: 'autocomplete-result-row-' + $data, href: '/packages/' + $data, title: $data }" tabindex="-1">
  | <div data-bind="attr:{ id: 'autocomplete-container-' + $data }" class="autocomplete-results-row">
  | </div>
  | </a>
  | </div>
  | 
  | </script>
  |  
  | </div>
  | </div>
  | </div>
  | </div>
  | </form>
  | </div>
  | </div>
  | </nav>
  |  
  |  
  |  
  |  
  |  
  | <div id="skippedToContent">
  |  
  |  
  | <section role="main" class="container main-container">
  | <div class="row page-error">
  | <div class="col-xs-12 col-sm-offset-1 col-sm-10 ms-fontWeight-light">
  | <p class="oops">Oops!</p>
  | <p class="error-title">Error 500 - Internal Server Error</p>
  | <div class="error-text">
  | <div class="text-main">
  |  
  | <p>An error occurred while processing your request. We really messed up this time...</p>
  | </div>
  | <div class="text-subtext">
  |  
  | <p>We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please <a href="https://github.com/PowerShell/PowerShellGallery/issues">file a bug!</a></p>
  | </div>
  | </div>
  |  
  | <p class="error-action">Get me out of here! <a href="/">Go home</a></p>
  | <p class="error-action">Wondering if PowerShell Gallery is down? <a href="https://aka.ms/psgallery-status">Check our status</a></p>
  | <p class="error-action">Looking for a package? <a href="/packages">Try searching</a></p>
  | <p class="error-action">Package you're looking for doesn't exist? <a href="https://aka.ms/psgallery-publishitem">Make one</a></p>
  | <p class="error-action">Pretty sure we messed up? <a href="https://aka.ms/psgallery-issues">File a bug</a></p>
  | </div>
  | </div>
  | </section>
  |  
  | </div>
  | <footer class="footer">
  | <div class="container footer-container" >
  | <div class="row">
  | <div class="hidden-xs footer-heading">
  | </div>
  | </div>
  | <div class="row">
  | <div class="col-sm-offset-1 col-sm-1 footer-heading">
  | <span><a href="/policies/Contact">Contact Us</a></span>
  | </div>
  | <div class="col-sm-1 footer-heading">
  | <span><a href="/policies/Terms">Terms of Use</a></span>
  | </div>
  | <div class="col-sm-1 footer-heading">
  | <span><a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy Policy</a></span>
  | </div>
  | <div class="col-sm-1 footer-heading">
  | <span><a href="https://aka.ms/psgallery-status/">Gallery Status</a></span>
  | </div>
  | <div class="col-sm-1 footer-heading">
  | <span><a href="https://github.com/PowerShell/PowerShellGallery/issues">Feedback</a></span>
  | </div>
  | <div class="col-sm-1 footer-heading">
  | <span><a href="https://aka.ms/PSGalleryPreviewFAQ">FAQs</a></span>
  | </div>
  | <div class="col-sm-4 footer-heading">
  | <span class="footer-heading-last">&copy; 2022 Microsoft Corporation</span>
  | </div>
  | </div>
  | </div>
  | </footer>
  |  
  | <script src="/Scripts/gallery/site.min.js?v=yowUC4LjtuEDFqBbt8mrSvw5D4Wp7o0dyNkck0RyrPs1"></script>
  |  
  |  
  | </body>
  | </html>
 

<br class="Apple-interchange-newline">
</body>
</html><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    

    <title>
        PowerShell Gallery
        | Internal Server Error
    </title>

    <link href="[/favicon.ico](https://www.powershellgallery.com/favicon.ico)" rel="shortcut icon" type="image/x-icon" />
        <link title="https://www.powershellgallery.com" type="application/opensearchdescription+xml" href="[/opensearch.xml](https://www.powershellgallery.com/opensearch.xml)" rel="search">

    <link href="[/Content/gallery/css/site.min.css?v=PiyChSWpJyC8Kpz_ZV5FuONZ0GHHOfH16uZN51B4pbI1](https://www.powershellgallery.com/Content/gallery/css/site.min.css?v=PiyChSWpJyC8Kpz_ZV5FuONZ0GHHOfH16uZN51B4pbI1)" rel="stylesheet"/>

    <link href="[/Content/gallery/css/branding.css?v=1.2](https://www.powershellgallery.com/Content/gallery/css/branding.css?v=1.2)" rel="stylesheet"/>

    
    
    

    

    
    
    
                
            <script type="text/javascript">
                var appInsights = window.appInsights || function (config) {
                    function s(config) {
                        t[config] = function () {
                            var i = arguments;
                            t.queue.push(function () { t[config].apply(t, i) })
                        }
                    }

                    var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u;
                    for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) s("track" + i.pop());
                    return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) {
                        var s = u && u(config, r, f, e, o);
                        return s !== !0 && t["_" + i](config, r, f, e, o), s
                    }), t
                }({
                    instrumentationKey: '50d4abc3-17d3-4a1b-8361-2d1e9ca8f6d5',
                    samplingPercentage: 100
                });

                window.appInsights = appInsights;
                appInsights.trackPageView();
            </script>

</head>
<body role="presentation">
    

<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <a href="[#](https://www.powershellgallery.com/Errors/500?aspxerrorpath=/%3Cscript%3Ealert(%22SleepTheGod%22);%3C/script%3E#)" id="skipToContent" class="showOnFocus" title="Skip To Content">Skip To Content</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-1 col-sm-2">
                <div class="navbar-header">
                    <a href="[/](https://www.powershellgallery.com/)" class="nvabar-header-aLink">
                        <img class="navbar-logo img-responsive" alt="PowerShell Gallery Home"
                             src="[/Content/Images/Branding/psgallerylogo.svg](https://www.powershellgallery.com/Content/Images/Branding/psgallerylogo.svg)"
                                 onerror="this.src='https://powershellgallery.com/Content/Images/Branding/psgallerylogo.png'; this.onerror = null;"
 />
                    </a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" title="Open Main Menu and profile dropdown">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
            <div class="col-sm-12 col-md-8 special-margin-left">
                <div id="navbar" class="navbar-collapse collapse" role="navigation" aria-label="Navigation Bar">
                    <table role="presentation">
                        <tr>
                            <td colspan="3">
                                <ul class="nav navbar-nav" role="tablist">
                                        <li class="" role="presentation">
        <a role="tab" aria-selected="false" href="[/packages](https://www.powershellgallery.com/packages)" target="" aria-label="Packages">
            <span aria-hidden="true">Packages</span>
        </a>
    </li>

                                        <li class="" role="presentation">
        <a role="tab" aria-selected="false" href="[/packages/manage/upload](https://www.powershellgallery.com/packages/manage/upload)" target="" aria-label="Publish">
            <span aria-hidden="true">Publish</span>
        </a>
    </li>

    <li class="" role="presentation">
        <a role="tab" aria-selected="false" href="[/stats](https://www.powershellgallery.com/stats)" target="" aria-label="Statistics">
            <span aria-hidden="true">Statistics</span>
        </a>
    </li>
                                                                            <li class="" role="presentation">
        <a role="tab" aria-selected="false" href="[https://go.microsoft.com/fwlink/?LinkID=825202&amp;clcid=0x409](https://go.microsoft.com/fwlink/?LinkID=825202&clcid=0x409)" target="_blank" aria-label="Documentation">
            <span aria-hidden="true">Documentation</span>
        </a>
    </li>

                                </ul>
                            </td>
                            <td colspan="1" class="td-align-topright">
                                    <ul class="nav navbar-nav navbar-right" role="tablist">
    <li class="" role="presentation">
        <a role="tab" aria-selected="false" href="[/users/account/LogOn?returnUrl=%2FErrors%2F500%3Faspxerrorpath%3D%2F%253Cscript%253Ealert%28%2522SleepTheGod%2522%29%3B%253C%2Fscript%253E](https://www.powershellgallery.com/users/account/LogOn?returnUrl=%2FErrors%2F500%3Faspxerrorpath%3D%2F%253Cscript%253Ealert%28%2522SleepTheGod%2522%29%3B%253C%2Fscript%253E)" target="" aria-label="Sign in">
            <span aria-hidden="true">Sign in</span>
        </a>
    </li>
                                    </ul>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

        <div class="container-fluid search-container">
            <div class="row" id="search-row">
                <form aria-label="Package search bar" action="/packages" method="get">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-offset-1 col-sm-2"></div>
                            <div class="col-sm-12 col-md-8">
                                <div class="form-group special-margin-left">
                                    <label for="search">Search PowerShell packages:</label>
<div class="input-group"  role="presentation">
    <input name="q" type="text" class="form-control ms-borderColor-blue search-box" id="search" aria-label="Enter packages to search, use the arrow keys to autofill."
           placeholder="PowerShellGet, Get-AzVM, etc..." autocomplete="on"
           value=""
           />
    <span class="input-group-btn">
        <button class="btn btn-default btn-search ms-borderColor-blue ms-borderColor-blue--hover" type="submit"
                title="Search PowerShell packages" aria-label="Search PowerShell packages">
            <span class="ms-Icon ms-Icon--Search" aria-hidden="true"></span>
        </button>
    </span>
</div>

                                    <div id="autocomplete-results-container" class="text-left" tabindex="0"></div>

<script type="text/html" id="autocomplete-results-row">
    
    
    <div class="col-sm-4 autocomplete-row-id autocomplete-row-data">
        <span data-bind="attr: { id: 'autocomplete-result-id-' + $data.PackageRegistration.Id, title: $data.PackageRegistration.Id }, text: $data.PackageRegistration.Id"></span>
    </div>
    <div class="col-sm-4 autocomplete-row-downloadcount text-right autocomplete-row-data">
        <span data-bind="text: $data.DownloadCount + ' downloads'"></span>
    </div>
    <div class="col-sm-4 autocomplete-row-owners text-left autocomplete-row-data">
        <span data-bind="text: $data.OwnersString + ' '"></span>
    </div>
    
    
    <div class="col-sm-12 autocomplete-row-id autocomplete-row-data">
        <span data-bind="attr: { id: 'autocomplete-result-id-' + $data, title: $data  }, text: $data"></span>
    </div>
    
    
</script>

<script type="text/html" id="autocomplete-results-template">
    
    <div data-bind="foreach: $data.data" id="autocomplete-results-list">
        <a data-bind="attr: { id: 'autocomplete-result-row-' + $data, href: '/packages/' + $data, title: $data }" tabindex="-1">
            <div data-bind="attr:{ id: 'autocomplete-container-' + $data }" class="autocomplete-results-row">
            </div>
        </a>
    </div>
    
</script>

                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
</nav>

    <div id="skippedToContent">
        

    <section role="main" class="container main-container">
        <div class="row page-error">
            <div class="col-xs-12 col-sm-offset-1 col-sm-10 ms-fontWeight-light">
                <p class="oops">Oops!</p>
                <p class="error-title">Error 500 - Internal Server Error</p>
                <div class="error-text">
                    <div class="text-main">
                        
<p>An error occurred while processing your request. We really messed up this time...</p>
                    </div>
                        <div class="text-subtext">
                            
<p>We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please <a href="https://github.com/PowerShell/PowerShellGallery/issues">file a bug!</a></p>
                        </div>
                </div>

                <p class="error-action">Get me out of here! <a href="[/](https://www.powershellgallery.com/)">Go home</a></p>
                <p class="error-action">Wondering if PowerShell Gallery is down? <a href="https://aka.ms/psgallery-status">Check our status</a></p>
                <p class="error-action">Looking for a package? <a href="[/packages](https://www.powershellgallery.com/packages)">Try searching</a></p>
                <p class="error-action">Package you're looking for doesn't exist? <a href="https://aka.ms/psgallery-publishitem">Make one</a></p>
                <p class="error-action">Pretty sure we messed up? <a href="https://aka.ms/psgallery-issues">File a bug</a></p>
            </div>
        </div>
    </section>

    </div>
    <footer class="footer">
    <div class="container footer-container" >
        <div class="row">
            <div class="hidden-xs footer-heading">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-1 col-sm-1 footer-heading">
                <span><a href="[/policies/Contact](https://www.powershellgallery.com/policies/Contact)">Contact Us</a></span>
            </div>
            <div class="col-sm-1 footer-heading">
                <span><a href="[/policies/Terms](https://www.powershellgallery.com/policies/Terms)">Terms of Use</a></span>
            </div>
            <div class="col-sm-1 footer-heading">
                <span><a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy Policy</a></span>
            </div>
            <div class="col-sm-1 footer-heading">
                <span><a href="https://aka.ms/psgallery-status/">Gallery Status</a></span>
            </div>
            <div class="col-sm-1 footer-heading">
                <span><a href="https://github.com/PowerShell/PowerShellGallery/issues">Feedback</a></span>
            </div>
            <div class="col-sm-1 footer-heading">
                <span><a href="https://aka.ms/PSGalleryPreviewFAQ">FAQs</a></span>
            </div>
            <div class="col-sm-4 footer-heading">
                <span class="footer-heading-last">&copy; 2022 Microsoft Corporation</span>
            </div>
        </div>  
    </div>
</footer>

    <script src="[/Scripts/gallery/site.min.js?v=yowUC4LjtuEDFqBbt8mrSvw5D4Wp7o0dyNkck0RyrPs1](https://www.powershellgallery.com/Scripts/gallery/site.min.js?v=yowUC4LjtuEDFqBbt8mrSvw5D4Wp7o0dyNkck0RyrPs1)"></script>

    
</body>
</html>`

**Comment by SydneyhSmith** [comment]
Thanks @SleepTheGod could you please provide additional information about the issue you were having/what you were expecting?

**Comment by SleepTheGod** [comment]
Not sure was just bored really sorry forgot about this I'm the worse at responding
