### ISSUE TITLE
No way to sign in with different account

### ISSUE THREAD

**Issue by deadlydog** [PowerShell/PowerShellGallery#23]
Our company uses Azure ADFS integration, but I use a personal account for the PowerShell Gallery. When I go to https://www.powershellgallery.com/users/account/LogOn and choose to `Sign in with Microsoft` it does not prompt me for which account I want to sign in as. Instead it tries to sign me in using my work email address, and when it cannot find an associated account it asks me to provide a username so it can create one. There does not seem to be any way for me to choose to sign in using a different email address; namely my personal one. Many other Microsoft sites prompt which account I want to sign in as before attempting to sign me in. The PowerShell Gallery website seems to be missing this functionality.

I was able to fix this by going to another Microsoft website (visualstudio.com) and signing out of my work account from there. Then when attempting to sign in to the PowerShell Gallery website it prompted me for which address I wanted to use. It seems silly that I need to go to some other website to do this though and cannot do it from the PowerShell Gallery website.

**Comment by bmanikm** [comment]
The workaround is to start your browser in-private or incognito (depending on browser).

**Comment by seanmcne** [comment]
@bmanikm this isn't a great workaround especially when we use this for work and we use a live/outlook.com identity for some things.  Any other workarounds or ways to save multiple identities instead of automatically assuming that we should just login whatever identity is _most convenient_?

**Comment by deadlydog** [comment]
The Azure ADFS login does seem to prompt me now after I logged in with my 2nd account. It seems like if the Azure login page "knows" (from cookies maybe?) that you have 2 accounts, it will prompt you for which one you want to use, but if it only knows about a single account it doesn't prompt you if you want to log in either a different account; it just tries to log you in using the one it knows about. That's likely a problem with the Azure ADFS login page that can't be fixed by the PowerShell Gallery folk, but providing a button to log you out of your current MS account (just like when hitting Logout on visualstudio.com) when it detects that you're signed in with an MS account and it doesn't have a PowerShell Gallery account associated with it would be a good solution.

**Comment by SydneyhSmith** [comment]
Closing this issue as it is resolved now (users are prompted for which account they would like)
