### ISSUE TITLE
https://www.poshtestgallery.com/ is currently timing out

### ISSUE THREAD

**Issue by gurnec** [PowerShell/PowerShellGallery#231]
I've tried connecting from multiple U.S. locations, and it's timing out on the initial TCP connect (no response to SYNs). It successfully resolves to `20.106.248.71`.

**Comment by SydneyhSmith** [comment]
The poshtestgallery is a test gallery for the PowerShell Gallery deployments, and is no longer available externally due to a change in policy

**Comment by gurnec** [comment]
OK, thank you for the answer.
