### ISSUE TITLE
Web page: Packages "Sort by" doesn't do anything

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShellGallery#236]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. Open a browser in guest mode to ensure no conflicting addons or history.
2. Go to https://www.powershellgallery.com/packages
3. Change "Sort By" to anything but the default value, nothing happens.

Also observe that changing "sort by" triggers no network activity when developer options (F12) is opened.

### Expected behavior

```console
List of packages should change sorting.
```

### Actual behavior

```console
Nothing happens.
```

### Environment data

```PowerShell
PowerShell Gallery web page.
```

### Version

220922

### Visuals

Default

![image](https://user-images.githubusercontent.com/6450056/191754326-c4f9d432-4438-444d-9983-6d4f3857cff5.png)

After changing "Sort By" to "Recent"

![image](https://user-images.githubusercontent.com/6450056/191754396-46ab9b92-5d1f-4cba-bc02-f2251304d911.png)

**Comment by alerickson** [comment]
Thanks @o-l-a-v for bringing this to our attention!  It looks like that functionality is not working at all right now.  We'll get on tackling this issue.

**Comment by alerickson** [comment]
We'll have an update for you on this by the end of the week!

**Comment by alerickson** [comment]
Quick update:  we have this bug resolved now, and hopefully get this fix deployed in the next week.

**Comment by alexandair** [comment]
11 days later, the fix is still waiting to be deployed. :(

**Comment by anamnavi** [comment]
@alexandair @o-l-a-v we'll have a temporary fix for this by tomorrow and then a more permanent fix by the end of the month. Thanks for your patience!

**Comment by datenschieber** [comment]
Same problem again...

**Comment by alexandair** [comment]
Broken again?

**Comment by datenschieber** [comment]
Yes. Exactly the same problem again.
