### ISSUE TITLE
powershell gallery search does not return results

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [PowerShell/PowerShellGallery#239]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

powershell gallery search does not return results even though the item is present in the gallery.

### Expected behavior

```console
The following function is present in the gallery:

https://www.powershellgallery.com/packages/Posh-IBWAPI/1.4/Content/Private%5CFormat-Columns.ps1

Search for it should return results
```

### Actual behavior

```console
No results
```

### Environment data

```PowerShell
https://www.powershellgallery.com/packages/Posh-IBWAPI/1.4/Content/Private%5CFormat-Columns.ps1
https://www.powershellgallery.com/packages?q=format-columns
```

### Version

https://www.powershellgallery.com/packages?q=format-columns

### Visuals

<img width="585" alt="image" src="https://user-images.githubusercontent.com/24302271/197439860-c337c7d2-d7b5-4f25-8c5d-e76aacbf4f89.png">

**Comment by alerickson** [comment]
Hi @Konstantin-Glukhov, we actually only support searching for modules and scripts, not the contents of modules or scripts, that's why `Format-Columns` does not return results.  Please let us know if you're having any other issues with returned results.

**Comment by Konstantin-Glukhov** [comment]
Is Format-Columns.ps1 considered to be a script name? Should it be found?

**Comment by Konstantin-Glukhov** [comment]
Could you provide instructions how I can install this module in PowerShell 7.2.7? (Please don't send me to read manuals! I already read all of them and cannot figure out how to do this simple task.)
