### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by tomgron** [PowerShell/PowerShellGallery#24]
https://www.powershellgallery.com/api/v2/ has no packages available (from EU)

**Comment by bmanikm** [comment]
@tomgron Could you please provide more details like Fiddler traces?

**Comment by tomgron** [comment]
Well, I can push a screenshot :

![image](https://user-images.githubusercontent.com/1743381/45864725-9d2ae680-bd83-11e8-94ca-fd43794243ce.png)

**Comment by tomgron** [comment]
Sorry, apparently the linking wasn't working correctly - the url of https://www.powershellgallery.com/api/v2/Packages/ seems to work ok.
