### ISSUE TITLE
Web page issue #236 reappeared

### ISSUE THREAD

**Issue by datenschieber** [PowerShell/PowerShellGallery#244]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Problem as described in closed issue #236 reappeared. Steps to to reproduce still valid.

### Expected behavior

```console
List of packages should change sorting.
```

### Actual behavior

```console
Nothing happens.
```

### Environment data

```PowerShell
https://www.powershellgallery.com/packages
```

### Version

n/a

### Visuals

See issue #236

**Comment by anamnavi** [comment]
This should be fixed now, if you still see it please let us know. Thanks!
