### ISSUE TITLE
Release Notes of the package not shown in the UI

### ISSUE THREAD

**Issue by bganapa** [PowerShell/PowerShellGallery#26]
I believe the release notes of the packages were shown in the  previous old UI, i do not see it any more..

may be i have seen it only in the nuget like below?
https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/

**Comment by JKeithB** [comment]
Yes, they are there, but you have to expand the Package Details section to see them.

**Comment by bganapa** [comment]
Thanks!
