### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by DRSchlaubi** [PowerShell/PowerShellGallery#261]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Open https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md

### Expected behavior

```console
The website works
```

### Actual behavior

```console
"Our services aren't available right now"
```

### Error details

```console
"Our services aren't available right now"
```

### Environment data

```PowerShell
Webbrowser
```

### Version

browser

**Comment by passionInfinite** [comment]
Confirmed Module installation using CLI but that's is also not working.

**Comment by passionInfinite** [comment]
Seems like it is back up now.
