### ISSUE TITLE
I can't login with my Microsoft Account

### ISSUE THREAD

**Issue by doggy8088** [PowerShell/PowerShellGallery#266]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

1. Go to https://www.powershellgallery.com/. Click **Sign in**.

    ![image](https://github.com/PowerShell/PowerShellGallery/assets/88981/a7d1f14b-117f-4326-8842-90011849775c)

2. Click **Sign in with Microsoft**

    ![image](https://github.com/PowerShell/PowerShellGallery/assets/88981/ef8cb1e0-0eff-47fc-a753-62a1511839f3)

3. Enter my Hotmail account ( Microsoft Account )

    ![image](https://github.com/PowerShell/PowerShellGallery/assets/88981/3ec06d44-62a7-4600-9404-753eaf161421)

4. I can't login.

    ![image](https://github.com/PowerShell/PowerShellGallery/assets/88981/e6118eea-4c95-447d-8b98-75a22bb80d3a)

### Expected behavior

```console
I expected to login into PowerShell Gallery site. I have a few package managed in my account. I can login before.
```

### Actual behavior

```console
I can't login.
```

### Error details

```console
See `Steps to reproduce`.
```

### Environment data

```PowerShell
N/A
```

### Version

N/A

**Comment by MichaelMcCool** [comment]
I am having a similar issue. I'm trying to log into PowerShellGallery with my personal Microsoft account so I can refresh my API key and update a module that I created. After signing in, I receive an "unknown error".
![image](https://github.com/PowerShell/PowerShellGallery/assets/83596075/7ebce121-2f93-4e37-9342-14d5aa5d343c)

 When trying to "recover" the login, the I provide the username, and after entering the email address, nothing happens. The process halts at that point.
![image](https://github.com/PowerShell/PowerShellGallery/assets/83596075/0f9bc9fc-ef6c-46fd-8483-501c2b4025c4)

**Comment by alerickson** [comment]
@MichaelMcCool can you share the URL after clicking on "Sign in with Microsoft"?  Should look something like: 
![image](https://github.com/PowerShell/PowerShellGallery/assets/25858831/eb1b5f56-8e72-44c8-b1f6-0f3cf6dced31)

**Comment by MichaelMcCool** [comment]
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d53deec6-b5c5-4953-8d80-73d001fd31e5&redirect_uri=https%3A%2F%2Fwww.powershellgallery.com%2Fusers%2Faccount%2Fauthenticate%2Freturn&response_type=code%20id_token&scope=openid%20profile%20email&state=OpenIdConnect.AuthenticationProperties%3DpX4AHrDbco4bFiFXUpkbIZ8G8Y-SYa9diRutmL1gEWhbZy7X45cHTZ-gKK6u8k6vEoxsj2dk49h5t4j4zj_ziv0F3dmLBC_hAmTk2JE_uckY5o3Gl_PdjeygQsSHGP7uPsXieOjtllr56kME8rDesa4BmMLoCa1NYwJCuCAwQfRNDY7mV5SlHgAQbJFnU3iXvyPXfzy9DAl4uMb59Y26r7zpkvBycTOltbpLLQFCpt6sOMDNX10_lVmCmdFPEDXoQViD0Gl0IobhuPYPG1G2pv6vpoVKOordPeZZCsmm3qx7KF0v7BGY4PpxLN9Iy44R&response_mode=form_post&nonce=638525404726962004.YzZjYzM3MjItY2IzMS00NzNjLWE5YzctOTQ3MDlhNWRmYjkxZTNhZWJkOWUtZjJhYS00MDdjLTgxNzItYTMwMjViMWRmMmZm&acr_values=urn%3Amicrosoft%3Apolicies%3Amfa%20urn%3Amicrosoft%3Apolicies%3Adefault&prompt=select_account&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

**Comment by alerickson** [comment]
@MichaelMcCool are you still encountering this issue?  I was able to repro the "unknown error" issue yesterday, but was also still able to log in.  This morning I wasn't even able to hit that.  What's the domain you're using for your email address?

**Comment by MichaelMcCool** [comment]
I tried an incognito window again today, and I am now able to log in successfully. Whatever the issue was appears to now be fixed.

**Comment by midhunmonachan** [comment]
I'm getting the same error now. I tried different accounts, different browsers, cleared all cachs. But all ends up in "Unknown error"!

**Comment by alerickson** [comment]
@midhunmonachan could you send an email to psgalleryadmin@microsoft.com with your username and email addresses?

**Comment by doggy8088** [comment]
It's working now.
