### ISSUE TITLE
Install-Module sample command line uses non-existent -AllowPrerelease flag

### ISSUE THREAD

**Issue by chwarr** [PowerShell/PowerShellGallery#27]
The Install-Module sample command line for a [pre-release package](https://www.powershellgallery.com/packages/PackageManagement/1.2.0-preview) is:

>    PS> Install-Module -Name PackageManagement -AllowPrerelease

`-AllowPrerelease` is not a switch that the `Install-Module` that is shipped in current versions of Windows 10 appears to understand.

The example command box has a link to the documentation for [`Install-Module`](https://aka.ms/InstallModule): this also does not mention `-AllowPrerelease`.

If a newer version of `Install-Module` is needed for `-AllowPrerelease` consider documenting this and explaining/linking to [installation instructions](https://docs.microsoft.com/en-us/powershell/gallery/installing-psget). I've searched this entire repository for "AllowPrerelease" and found only [one hit in a helper script](https://github.com/PowerShell/PowerShellGallery/search?q=-AllowPrerelease+OR+AllowPrerelease&unscoped_q=-AllowPrerelease+OR+AllowPrerelease).

```
PS> Get-Help Install-Module

NAME
    Install-Module

SYNTAX
    Install-Module [-Name] <string[]> [-MinimumVersion <version>] [-MaximumVersion <version>] [-RequiredVersion <version>] [-Repository
    <string[]>] [-Credential <pscredential>] [-Scope {CurrentUser | AllUsers}] [-Proxy <uri>] [-ProxyCredential <pscredential>]
    [-AllowClobber] [-SkipPublisherCheck] [-Force] [-WhatIf] [-Confirm]  [<CommonParameters>]

    Install-Module [-InputObject] <psobject[]> [-Credential <pscredential>] [-Scope {CurrentUser | AllUsers}] [-Proxy <uri>]
    [-ProxyCredential <pscredential>] [-AllowClobber] [-SkipPublisherCheck] [-Force] [-WhatIf] [-Confirm]  [<CommonParameters>]

...

PS> Get-Command Install-Module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     1.0.0.1    PowerShellGet

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

`Install-Module` from PowerShellGet version 2.0.0 does have `-AllowPrerelease`.

**Comment by edyoung** [comment]
Yes, a newer version of PowerShellGet is required to specify -AllowPreRelease. 

Note that the code and issues for PowerShellGet are in the PowerShellGet repo : https://github.com/PowerShell/PowerShellGet. This is for the PowerShell Gallery (one of the web repositories PowerShellGet can download packages from). You would find more information there. 

I will pass on the issue with documentation to the right people
