### ISSUE TITLE
Download stats stuck at 0 in ``Microsoft.Graph``

### ISSUE THREAD

**Issue by timayabi2020** [PowerShell/PowerShellGallery#272]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Download stats stuck at zero for ``Microsoft.Graph``

### Expected behavior

```console
Should show stats even after manual download.
```

### Actual behavior

```console
Stats stuck at zero downloads
```

### Error details

```console
NA
```

### Environment data

```PowerShell
NA
```

### Version

NA

### Visuals

<img width="436" alt="image" src="https://github.com/PowerShell/PowerShellGallery/assets/10947120/ce2ed805-1e03-4e3c-947b-8fef5bf262b5">

**Comment by alerickson** [comment]
This issue is resolved now.  @timayabi2020 thanks for opening and I apologize for the late response.
