### ISSUE TITLE
Issue downloading Modules since maintenance started

### ISSUE THREAD

**Issue by PckgrTom** [PowerShell/PowerShellGallery#279]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Attempt to install any module from ps gallery

### Expected behavior

```console
Module should install like normal
```

### Actual behavior

```console
Install-Package: No match was found for the specified search criteria and module name 'Microsoft.WinGet.Client'. Try Get-PSRepository to
see all available registered module repositories.
```

### Error details

```console
Install-Package: No match was found for the specified search criteria and module name 'Microsoft.WinGet.Client'. Try Get-PSRepository to
see all available registered module repositories.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.3880
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3880
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

5.1.22621.3880

**Comment by shipsides-sparknel** [comment]
+1 for me on this one too

**Comment by PckgrTom** [comment]
> +1 for me on this one too

It started working for me again but then a git runner just failed with the error so might be intermittent.

**Comment by dstace** [comment]
+1 from me. Initially it appeared to just be modules, however I have had Install-Script intermittently failing as well.

**Comment by nzaware** [comment]
+1 facing issue while downloading modules. 
![image](https://github.com/user-attachments/assets/6f173f83-d34d-4bae-b888-58c9ce4ef69d)

**Comment by theologos7** [comment]
Using `Install-PSResource` I was getting a similar error. The API call that PSRG uses is: 

`https://www.powershellgallery.com/api/v2/FindPackagesById()?$filter=Id+eq+%27ComputerManagementDsc%27+and+NormalizedVersion+eq+%279.1.0%27&$inlinecount=allpages&id=%27ComputerManagementDsc%27`

Which was returning an error.

`
Response status code does not indicate success: 999.' Request sent: 'https://www.powershellgallery.com/api/v2/FindPackagesById()?$filter=Id+eq+%27ComputerManagementDsc%27+and+NormalizedVersion+eq+%279.1.0%27&$inlinecount=allpages&id=%27ComputerManagementDsc%27
`

This set of query parameters was still working however:

`https://www.powershellgallery.com/api/v2/FindPackagesById()?id=%27ComputerManagementDsc%27&$filter=IsLatestVersion`

So I think that there is indeed something transient during maintenance as the first API call is working again through PSRG. Just going to wait it out. 😄

**Comment by xv-aleksandr-b** [comment]
I'm having same issue now with `Install-Package` command...

**Comment by nrv-96** [comment]
Dear Contributor,

Do we have a clone site or backup of PSGallery to prevent downtime and allow users to download from the backup site?

If you find this comment useful, please react with a thumbs-up 👍so that repository contributors understand the importance of keeping the site alive.

**Comment by dagstuan** [comment]
Seeing the same thing. Also attempting to browse certain packages such as `AzureRM.Profile` on the web comes back with a WAF error: https://www.powershellgallery.com/packages/AzureRM.Profile/

<img width="547" alt="image" src="https://github.com/user-attachments/assets/425f989d-cf49-4b0f-bd78-36710766271b">

**Comment by guillermocb** [comment]
Failing for us too

Trying to get this file from our pkg repo: /nuget/v3/flat2/microsoft.applicationinsights.profiler.aspnetcore/index.json 

{"$id": "1","innerException": null,"message": "Failed to retrieve data from the upstream package source '[https://www.powershellgallery.com/api/v2/':](https://www.powershellgallery.com/api/v2/%27:) 999 ()","typeName": "Microsoft.VisualStudio.Services.Packaging.ServiceShared.Upstream.PublicUpstreamFailureException, Microsoft.VisualStudio.Services.Packaging.ServiceShared","typeKey": "PublicUpstreamFailureException","errorCode": 0,"eventId": 3000}

**Comment by o-l-a-v** [comment]
Discovered today that API requests with `$select` (to get less data and thus get a faster response + put less stress on the backend) suddenly also gives "".

* Does not work: <https://www.powershellgallery.com/api/v2/FindPackagesById()?id=%27Az.Accounts%27&$filter=IsLatestVersion%20and%20not%20IsPrerelease&$select=Authors,Published,RequireLicenseAcceptance,Tags,Version&semVerLevel=1.0.0>

* Works: <https://www.powershellgallery.com/api/v2/FindPackagesById()?id=%27Az.Accounts%27&$filter=IsLatestVersion%20and%20not%20IsPrerelease&semVerLevel=1.0.0>

**Comment by fentonfentonfenton** [comment]
+1

**Comment by Alexdc-12** [comment]
Same problem for me https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt.Profile/ shows blocked

PackageManagement\Save-Package : No match was found for the specified search criteria and module name 'MicrosoftPowerBIMgmt.Profile'. Try Get-PSRepository to see all available registered module repositories.

**Comment by camistein** [comment]
We are having issues with AzureRM.profile package :  https://www.powershellgallery.com/packages/AzureRM.profile/ . Shows blocked by firewall rules and we're unable to install package

**Comment by jpawlowski** [comment]
+1

**Comment by anastasiarSievo** [comment]
The same. This is kinda critical for us. Any ETA for the fix?

**Comment by DarrylHasieber** [comment]
> Same problem for me https://www.powershellgallery.com/packages/MicrosoftPowerBIMgmt.Profile/ shows blocked
> 
> PackageManagement\Save-Package : No match was found for the specified search criteria and module name 'MicrosoftPowerBIMgmt.Profile'. Try Get-PSRepository to see all available registered module repositories.

Same. Preventing ADO Pipeline from deploying reports.

**Comment by JonDibble** [comment]
+1

**Comment by guillermocb** [comment]
> Failing for us too
> 
> Trying to get this file from our pkg repo: /nuget/v3/flat2/microsoft.applicationinsights.profiler.aspnetcore/index.json 
> 
> {"$id": "1","innerException": null,"message": "Failed to retrieve data from the upstream package source '[https://www.powershellgallery.com/api/v2/':](https://www.powershellgallery.com/api/v2/%27:) 999 ()","typeName": "Microsoft.VisualStudio.Services.Packaging.ServiceShared.Upstream.PublicUpstreamFailureException, Microsoft.VisualStudio.Services.Packaging.ServiceShared","typeKey": "PublicUpstreamFailureException","errorCode": 0,"eventId": 3000}

Fixed, it works again for us. Thanks

**Comment by alerickson** [comment]
Thanks for reporting!  We added new company wide firewall policies and unfortunately a few of them are causing issues.  We've reverted all the recent changes as of roughly 4 hours ago, so folks should be unblocked by this issue now.
