### ISSUE TITLE
HELP! help and save docker module

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShellGallery#28]
https://github.com/Microsoft/Docker-PowerShell/

Docker module is very good module for management container and image.

now project is readonly,we can not download & installed from https://ci.appveyor.com/nuget/docker-powershell-dev

I expect PowerShell Gallery to include this module.

Request powershell-team rescue docker module

===================================
0.1.0.111 is latest version.
this version work normal in ps core 6.1 preview2,
but report error for any module-command in ps core 6.1 preview3,preview4
eg: "Get-Container : Docker API responded with status code=BadRequest, response=400 Bad Request: unsupported protocol version"

download the latest version of docker module https://files.cnblogs.com/files/piapia/docker_for_powershell_only_one.tar.gz

**Comment by edyoung** [comment]
Sorry, but the powershell gallery team is not in a position to take over maintenance of that module.
