### ISSUE TITLE
Unable to Login to PowerShell Gallery Website (Multiple Users)

### ISSUE THREAD

**Issue by syne0** [PowerShell/PowerShellGallery#286]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

- Attempt to login

### Expected behavior

```console
- You are logged in
```

### Actual behavior

```console
- You get an Error 500
```

### Error details

```console
Oops!

Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug!

Get me out of here! Go home

Wondering if PowerShell Gallery is down? Check our status

Looking for a package? Try searching

Package you're looking for doesn't exist? Make one

Pretty sure we messed up? File a bug
```

### Environment data

```PowerShell
N/A
```

### Version

N/A

### Visuals

![image](https://github.com/user-attachments/assets/5528a8d4-1799-4e1c-bd91-9fca58ef0985)

**Comment by syne0** [comment]
Asked a few coworkers to test and no one could log in or create an account successfully.

**Comment by devizer** [comment]
Same problem.

**Comment by alerickson** [comment]
This issue is resolved now.  Closing this as resolved, please let us know if you have any more issues.
