### ISSUE TITLE
Sign in with Microsoft account to https://www.powershellgallery.com/ results in Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by MirzaMujagic** [PowerShell/PowerShellGallery#288]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I get following error when i try to logon to PowershellGallery with "Microsoft Account" / @live.com on Windows 11 and Edge

Oops!
Error 500 - Internal Server Error
An error occurred while processing your request. We really messed up this time... 

### Expected behavior

```console
...
```

### Actual behavior

```console
Error 500 - Internal Server Error
```

### Error details

```console
Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug!

Get me out of here! Go home

Wondering if PowerShell Gallery is down? Check our status

Looking for a package? Try searching

Package you're looking for doesn't exist? Make one

Pretty sure we messed up? File a bug
```

### Environment data

```PowerShell
n/a
```

### Version

n/a

**Comment by alerickson** [comment]
@MirzaMujagic Thanks for opening this issue!  We found the issue and are mitigating now, you should be able to log in again in roughly 15 minutes.  I'll comment again shortly when this work is complete.

**Comment by alerickson** [comment]
This issue is resolved now.  Closing this as resolved, please let us know if you have any more issues.
