### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShellGallery#289]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Search not working

### Expected behavior

```console
threadjob
```

### Actual behavior

```console
no search results
```

### Environment data

```PowerShell
n/a
```

### Version

n/a

### Visuals

![image](https://github.com/user-attachments/assets/8ad5c88a-550a-438c-a78e-695b553b65b8)

**Comment by GregDomzalski** [comment]
This was broken for me earlier as well, but seems to have been recently fixed.

**Comment by ThomasNieto** [comment]
@alerickson search is not working again right now.

**Comment by SydneyhSmith** [comment]
We think this issue is now resolved
