### ISSUE TITLE
PoshTest Gallery is not sending the correct 'latest version' package information

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PowerShellGallery#36]
PoshTest Gallery is not sending the correct package information for "isLatestVersion" and "IsAbsoluteLatestVersion". 

I have a module, PMTestModule that takes a dependency on a module PMTestDepenency1.  There are two versions of this dependency, version 1.0 which is listed and version 1.0.1 which is unlisted.

Running ` Save-Package -name PMTestModule -source PoshTest -path . -requiredversion 1.0.2
`
Saves PMTestDependency1 version 1.0 instead of the latest version, 1.0.1.

Package Management's Nuget Provider iterates through all the versions of all the modules, but I noticed that when I print out the attributes for each module, PMTestDependency1 v1.0 has "IsLatestVersion" and "IsAbsoluteLatestVersion" attributes set to true, and PMTestDependency1 v.1.0.1 has the two set to false, when it should be the other way around. 

Ultimately this is preventing Package Management from saving or installing the latest version of a dependency if that version is unlisted.  

PoshTest is registered as:
![packagesource](https://user-images.githubusercontent.com/25858831/47682162-c875d200-db88-11e8-9ce9-7dcdf562ba0b.PNG)

![pkgerror](https://user-images.githubusercontent.com/25858831/47682918-23a8c400-db8b-11e8-92f5-7ee67990701d.PNG)

**Comment by alerickson** [comment]
Closing after discussion with @edyoung and @rebro-msft

**Comment by bmanikm** [comment]
`PMTestDependency1 v1.0 has "IsLatestVersion" and "IsAbsoluteLatestVersion" attributes set to true, and PMTestDependency1 v.1.0.1 (unlisted) has the two set to false.`

Above mentioned scenario is expected when newer versions are unlisted. Since 1.0.1 version got unlisted, this version's metadata should convey that it is not the latest version.
