### ISSUE TITLE
Find-Module and Install-Module without -AllowPrerelease switch returns -alpha version 

### ISSUE THREAD

**Issue by SaBomNim21** [PowerShell/PowerShellGallery#39]
When using Find-Module or Install-Module on a clean slate install:
`install-Module Microsoft.FastTrack.Migration`
Installs the **latest ALPHA version** not the production version
![image](https://user-images.githubusercontent.com/30178859/49522082-08a13200-f864-11e8-82cd-9f1efd34cf40.png)

Version              Name                                Repository           Description
-------              ----                                ----------           ----------- 
2.0.3                PowerShellGet                       PSGallery            PowerShell module with commands

**Comment by SaBomNim21** [comment]
Any update?  Looking to get a fix!

**Comment by SydneyhSmith** [comment]
@SaBomNim21 Thanks for filing this issues, I am having difficulty reproducing this issue on my machine and trying to figure out what is causing this, could you include $PSVersionTable? It is also possible that the module is not properly flagged as PreRelease, could you include the result of 
 (Get-InstalledModule Microsoft.FastTrack.Migration).AdditionalMetadata ? Thanks

**Comment by SaBomNim21** [comment]
summary                   : Enables Office 365 FastTrack customers to
manage migration services provided by Office FastTrack
SourceName                : PSGallery
installeddate             : 2018-12-05T17:52:53.8917394-07:00
copyright                 : (c) 2018 Microsoft. All rights reserved.
tags                      : FastTrack GDPR Microsoft Microsoft.FastTrack
PSModule
Type                      : Module
InstalledLocation         : C:\Program
Files\WindowsPowerShell\Modules\Microsoft.FastTrack.Migration\2.1.339
description               : Enables Office 365 FastTrack customers to
manage migration services provided by Office FastTrack
published                 : 1/1/1900 12:00:00 AM
PackageManagementProvider : NuGet
IsPrerelease              : True

I believe the issue is a limitation on how many record results the api is
returning - we had > 20 ALPHA versions with a higher version than the
release version - when we unlisted all of those the release version became
available again for install.  So I still believe this is a bug.

**Comment by SydneyhSmith** [comment]
Closing this issue as resolved by PackageManagement 1.2.4, will re-open if this is still an issue
