### ISSUE TITLE
PS Gallery Error 500 attempting to login to manage modules

### ISSUE THREAD

**Issue by SaBomNim21** [PowerShell/PowerShellGallery#40]
My microsoft v-dash account results in an Err 500 result but actually logs me in
![image](https://user-images.githubusercontent.com/30178859/49524073-4738eb80-f868-11e8-8f18-4d702d4cd480.png)

**Comment by SaBomNim21** [comment]
Note: Profile in upper right of image

**Comment by SydneyhSmith** [comment]
@SaBomNim21 Is this issue blocking you from reaching other pages in the Gallery once you are logged in?

**Comment by SaBomNim21** [comment]
No I can login - and then navigate to other pages - just ugly welcome page.

**Comment by edyoung** [comment]
We fixed the www-redirect issue a while back and I';m guessing that applies to this. If you can still repro feel free to reopen
