### ISSUE TITLE
Error 500 on Edit Profile in powershellgallery.com

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/PowerShellGallery#50]
Oops!

Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug! <--: This is us now

Get me out of here! Go home

Wondering if PowerShell Gallery is down? Check our status

Looking for a package? Try searching

Package you're looking for doesn't exist? Make one

Pretty sure we messed up? File a bug

**Comment by edyoung** [comment]
Bit more info? What is url you were on?

**Comment by JeremyTBradshaw** [comment]
@edyoung Certainly.  https://www.powershellgallery.com/account is the URL.  I sign-in, click my name, then View Profile from the dropdown.  Then I click the pencil to edit, which leads to this URL and has:
Oops!

Error 500 - Internal Server Error

An error occurred while processing your request. We really messed up this time...

We have logged the error and will look into it so that it doesn't happen again; however, if you keep seeing this page, please file a bug!

Get me out of here! Go home

Wondering if PowerShell Gallery is down? Check our status

Looking for a package? Try searching

Package you're looking for doesn't exist? Make one

Pretty sure we messed up? File a bug

**Comment by edyoung** [comment]
What's your account name?

**Comment by JeremyTBradshaw** [comment]
It's my this account (personal Microsoft account).

**Comment by edyoung** [comment]
I can't tell what your Microsoft account is from your GitHub logon name (or at least, I don't know how, if that is possible). What is your username in the actual PowerShell Gallery? (There's no JeremyTBradshaw )

**Comment by JeremyTBradshaw** [comment]
Sorry that is actually what it shows as my name, but otherwise it is my email address so I'll hold off on putting it here.  But by the way, since earlier the page is now working so the issue must have been resolve.

I'm all set.  Thanks for your help.
