### ISSUE TITLE
problems with Hash values

### ISSUE THREAD

**Issue by stumueller** [PowerShell/PowerShellGallery#53]
Im trying to install AzureRM.Profile and hitting the following error message:

Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.profile/5.8.3'.
Completed downloading 'AzureRM.profile'.
Hash for package 'AzureRM.profile' does not match hash provided from the server.

**Comment by SydneyhSmith** [comment]
@stumueller thanks for reporting this, it would be great if you could provide some re-pro info specifically the output of the commands:
```gmo PackageManagement, PowerShellGet -ListAvailable```

```$PSVersionTable```
and the command that you ran when you hit this errror

**Comment by SydneyhSmith** [comment]
Closing this as inactive, will reopen if this is still an issue
