### ISSUE TITLE
Problem with PSYAML

### ISSUE THREAD

**Issue by Phil-Factor** [PowerShell/PowerShellGallery#54]
This code I published a while back called  PSYAML was used without my permission for the module PSYAML  on this site. I wouldn't mind about this if it worked properly and if I had access to it to keep it up to date and working. It doesn't, and I don't. I have tried on several times to message the person credited with the copyright to alert him that the code needs mending, but your mail system seems to be broken. I keep getting the message that I failed 'Recapcha'.

**Comment by SydneyhSmith** [comment]
@Phil-Factor  The mail system should now be fixed, would you mind trying again and letting us know if it is working for you?

**Comment by edyoung** [comment]
Regarding psyaml package, if you believe this is copyright infringement you can request a takedown, but if it is under an open source license that doesn't usually apply. Otherwise I recommend publishing your version under another name.

**Comment by Phil-Factor** [comment]
Yes thanks. Mail working now. Hopefully, I'll get a reply and can sort out  the problem with the module.
