### ISSUE TITLE
PowerShellGallery.com statistics does not work at all

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShellGallery#59]
### Steps to Reproduce

1. Go to https://www.powershellgallery.com/stats/packages
2. See that statistics on packages are not available (screenshot below)
![image](https://user-images.githubusercontent.com/447485/58268743-040a0080-7d54-11e9-88b1-2eb1e4a6a054.png)

**Comment by edyoung** [comment]
Thanks, we're aware and working on a solution

**Comment by jzabroski** [comment]
@edyoung This is still broken...

**Comment by SteveL-MSFT** [comment]
We've made some changes to the backend to increase the processing units.  It's still working through the backlog, but appears to be catching up.

**Comment by jzabroski** [comment]
Thank you. As some feedback, I have noticed significant improvement in
PowerShell community relations over last 3 to 6 months. This is hopefully
the start of a wave of growth and good strategy. Thank you, Steve.

**Comment by SydneyhSmith** [comment]
Closing as resolved--thanks
