### ISSUE TITLE
TLS 1.0?

### ISSUE THREAD

**Issue by Daddio92116** [PowerShell/PowerShellGallery#66]
My customer is attempting to install/update a Windows Virtual Desktop powershell module but they block TLS 1.0.   Please update the website to the latest version of the protocol

**Comment by edyoung** [comment]
Hi, the powershell gallery site supports TLS 1.2 (you can check here https://www.ssllabs.com/ssltest/analyze.html?d=www.powershellgallery.com). It is more likely the client stack you are using to try and download the module is older and doesn't fully support newer TLS versions. This has an explanation of the issues and options: https://stackoverflow.com/questions/36265534/invoke-webrequest-ssl-fails

Please let us know if that works for you
