### ISSUE TITLE
Signed package support?

### ISSUE THREAD

**Issue by inthemedium** [PowerShell/PowerShellGallery#67]
When I try to push a signed package using `nuget.exe` I get the following error
> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (The package was signed. You must register the signing certificate to publish signed packages.).
2019-09-25T20:28:35.3824042Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() 

As far as I can tell, there is no place to register the signing certificate.

Is there a way to upload signed packages that I'm missing?

**Comment by alerickson** [comment]
No, you're right-- this is a bug in the gallery.  The gallery's forked from the NuGet gallery and after an upstream merge we inherited some things that we shouldn't have.  I made some changes and deployed to prod, could you let me know if you're still encountering this issue?

**Comment by inthemedium** [comment]
It'll probably be a few weeks before I can try again, as I ripped out the signing infrastructure for our package.

**Comment by alerickson** [comment]
No problem, we'll close the issue for now, but if you're still running into the problem we can reopen.
