### ISSUE TITLE
Invalid documentation link

### ISSUE THREAD

**Issue by Akaizoku** [PowerShell/PowerShellGallery#68]
The `Documentation` link from the menu bar is invalid:

- Target: https://go.microsoft.com/fwlink/?LinkID=825202&clcid=0x409
- Landing: https://docs.microsoft.com/en-us/powershell/gallery

- Expected: https://docs.microsoft.com/en-us/powershell/scripting/gallery/overview

**Comment by SydneyhSmith** [comment]
Closing this issue as fixed, thanks for reporting it @Akaizoku !
