### ISSUE TITLE
Documentation link on Item Page is confusing

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShellGallery#7]
The new description of the documentation link is better. Most customers expect that to link to go to documentation for the Item.

![image](https://user-images.githubusercontent.com/19415881/42050514-067e3956-7abe-11e8-946f-c326891c1283.png)

Question - How is this documentation link any different than the documentation link in the page header?

Suggestion - Keep the documentation link but make it clearer that is documentation for the deployment method selected. Also, make that link context sensitive. For example:

- On the **Install Module** tab link to https://docs.microsoft.com/powershell/module/powershellget/install-module
- On the **Azure Automation** tab link to https://docs.microsoft.com/powershell/gallery/how-to/working-with-items/deploy-to-azure-automation
- On the **Manual Download** tab link to https://aka.ms/psgallery-manualdownload

**Comment by sdwheeler** [comment]
@JKeithB For your review

**Comment by J0F3** [comment]
+1

**Comment by JKeithB** [comment]
Fixed in the latest update on PowerShellGallery.com

**Comment by JKeithB** [comment]
Example - see https://www.powershellgallery.com/packages/PowerShellGet/2.0.0 for an example.
