### ISSUE TITLE
Filters not working after going to page 2

### ISSUE THREAD

**Issue by riedyw** [PowerShell/PowerShellGallery#70]
Any filters that you set or unset on the main page of packages disappear when you go to the next page.

What's the purpose of the filters if they don't "stick" when you go from page to page?

This behavior occurs in both Chrome and Internet Explorer. Also occurs whether you are signed in or not.

**Comment by SydneyhSmith** [comment]
@riedyw thanks for opening this issue, agree that this is not a desired behavior at all and can be frustrating when searching for packages, we are tracking this work item with issue #49 so I will close as a duplicate---thanks!!
