### ISSUE TITLE
Fix links on first page "Learn" - "What is Powershell Gallery" and "Getting Started"

### ISSUE THREAD

**Issue by LUCScape** [PowerShell/PowerShellGallery#71]
To be fixed, on PowerShell Gallery homepage:

"What is PowerShell Gallery?"
old link:
https://docs.microsoft.com/en-us/powershell/gallery/overview
New link:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/overview

"Getting started"
old link:
https://docs.microsoft.com/en-us/powershell/gallery/getting-started
New link:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started

**Comment by alerickson** [comment]
These are fixed now, thanks!
