### ISSUE TITLE
Dead links on https://www.powershellgallery.com/ homepage

### ISSUE THREAD

**Issue by marcduiker** [PowerShell/PowerShellGallery#75]
It appears the __What is PowerShell Gallery?__ and __Getting started__ links on https://www.powershellgallery.com/ are dead.

Current:
https://docs.microsoft.com/en-us/powershell/gallery/overview
https://docs.microsoft.com/en-us/powershell/gallery/getting-started

Should be:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/overview
https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-6

**Comment by LesterCovax** [comment]
The "FAQ" link also points to an [extremely outdated page](https://github.com/PowerShell/PowerShellGallery/blob/master/PreviewReleaseNotes.md) regarding [preview.powershellgallery.com](https://preview.powershellgallery.com/) (dead link), instead of, well, providing a FAQ.

**Comment by alerickson** [comment]
Thanks!  We've got these fixed now :)

**Comment by LesterCovax** [comment]
@alerickson The FAQ link at the bottom of the page still directs to a GitHub page concerning preview.powershellgallery.  Apologies if changes were made but it just hasn't been pushed live yet.

**Comment by alerickson** [comment]
@LesterCovax yup, you're right, I missed that.  I'll get that in with the next deployment in the next 2 weeks.

**Comment by jaapbrasser** [comment]
Dead links on the homepage once again:
* https://docs.microsoft.com/en-us/powershell/gallery/getting-started
* https://docs.microsoft.com/en-us/powershell/gallery/overview

**Comment by alerickson** [comment]
@jaapbrasser we have this fixed, but we have a deployment freeze right now, so we can't get this out to production for the time being.
