### ISSUE TITLE
Getting Started Link - 404

### ISSUE THREAD

**Issue by StylusEaterCTP** [PowerShell/PowerShellGallery#78]
The "Getting Started" link results in a 404 at https://www.powershellgallery.com/ .

**Comment by brunodefrancavalli** [comment]
Yep still an issue :(

**Comment by StylusEaterCTP** [comment]
@brunodefrancavalli I'm not seeing a repo to submit a patch. Are you aware of one?

**Comment by brunodefrancavalli** [comment]
@StylusEaterCTP sorry I am not. :(

**Comment by SimonClendon** [comment]
Still broken. Just missing a forward slash.
    https://docs.microsoft.compowershell/scripting/gallery/getting-started
should be
    https://docs.microsoft.com/powershell/scripting/gallery/getting-started

**Comment by StylusEaterCTP** [comment]
Confirmed. Fixed.
