### ISSUE TITLE
What is PowerShell Gallery Link - 404

### ISSUE THREAD

**Issue by StylusEaterCTP** [PowerShell/PowerShellGallery#79]
The "What is PowerShell Gallery?" link results in a 404 at https://www.powershellgallery.com/ .

**Comment by bravo-kernel** [comment]
Confirmed

**Comment by alerickson** [comment]
Thanks! We've fixed this with the latest deployment.

**Comment by StylusEaterCTP** [comment]
Confirmed. Fixed.
