### ISSUE TITLE
Request for including ADLS Gen2 commands like New-AzDatalakeGen2FileSystem in Az.storage 1.9.1 version

### ISSUE THREAD

**Issue by sai3184** [PowerShell/PowerShellGallery#80]
I am aware of the fact that the ADLS Gen2 commands like New-AzDatalakeGen2FileSystem are already included as part of Az.storage 1.11.1, but we have a production environment using 1.9.1version of az.storage, This is our blocker and requesting you to provide a Hotfix version of the 1.9.1.

**Comment by alerickson** [comment]
Hi @sai3184, we only have control over the PowerShell Gallery, not the modules published to it.  If you'd like to get in touch with the module owners for Az.storage please go to "Contact Owners"  (https://www.powershellgallery.com/packages/Az.Storage/4.0.2-preview).

**Comment by alerickson** [comment]
@SydneyhSmith can you close this as well?
