### ISSUE TITLE
404 linked from release notes

### ISSUE THREAD

**Issue by jacobembree** [PowerShell/PowerShellGallery#81]
At https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.77
the link to https://msdn.microsoft.com/powershell/gallery/readme in the first paragraph is a 404.

**Comment by alerickson** [comment]
This description and broken link is actually coming from the module manifest.  I can't change this, but you can get in touch with the module owners (under "Contact Owners": https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.77) to let them know of this issue.

**Comment by alerickson** [comment]
@SydneyhSmith feel free to close this issue
