### ISSUE TITLE
Invalid link on home page for "Getting started"

### ISSUE THREAD

**Issue by metablaster** [PowerShell/PowerShellGallery#82]
At first I thought it's my DNS settings but the link doesn't seem to be valid:

**Getting started** on [PowerShellGallery ](https://www.powershellgallery.com)home page:
https://docs.microsoft.compowershell/scripting/gallery/getting-started

It should probably be:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?view=powershell-7

**Comment by alerickson** [comment]
Thanks!  This is resolved with the latest deployment.

**Comment by StylusEaterCTP** [comment]
Confirmed. Fixed. @metablaster please confirm and close.

**Comment by metablaster** [comment]
Thank you guys for update!

Yes I confirm, the link is updated.
