### ISSUE TITLE
Current version of module

### ISSUE THREAD

**Issue by cycloidmike** [PowerShell/PowerShellGallery#83]
How do we set the current version of the module in the powershell gallery?
When I use this link - [https://www.powershellgallery.com/packages/MicrosoftTeams/](https://www.powershellgallery.com/packages/MicrosoftTeams/) (forward slash at the end) it redirects me to version 1.0.3

But if I use this link - [https://www.powershellgallery.com/packages/MicrosoftTeams](https://www.powershellgallery.com/packages/MicrosoftTeams) (without a forward slash) it redirects me to version 1.0.4

When I search for the module (MicrosoftTeams) then it uses the link with a forward slash and directs me to version 1.0.3

**Comment by alerickson** [comment]
Hi, are you still encountering this issue?  Right now I'm getting redirected to the latest version (1.0.5) with both links.

**Comment by SydneyhSmith** [comment]
Closing as I am also unable to re-produce the issue, but more than happy to re-open if it is still occuring
