### ISSUE TITLE
Publish modules as 'unlisted'

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PowerShellGallery#85]
Suggestion to have modules published to the gallery as 'unlisted' so that the module can be tested, then officially listed.  This would be a good way to work around having a staging gallery.

Publish-module can take a parameter to publish -AsUnlisted

**Comment by ThomasNieto** [comment]
If the unlisted version fails testing there should be a way to remove or overwrite the version.

**Comment by alerickson** [comment]
@ThomasNieto agreed, something I was thinking of as a separate issue, but also related to this is: https://github.com/PowerShell/PowerShellGallery/issues/87

**Comment by JustinGrote** [comment]
I feel like Prerelease already sort of accomplishes this goal, and you can 'delist' modules so they don't show up in PS gallery if they are broken or unnecessary for whatever reason.

I know the major reason modules can't be deleted is in case someone takes a dependency on one, so it doesn't just suddenly 'disappear', but they can already be unlisted in the API.

You could publish the module as prerelease and then delist it immediately as a workaround?

**Comment by SydneyhSmith** [comment]
Looks like we are already tracking this request with issue #3 so going to close this one as a duplicate
