### ISSUE TITLE
ERROR - Defining Policy -New-AzPolicyAssignment - Can't use inline policy defination

### ISSUE THREAD

**Issue by Neelkamal10** [PowerShell/PowerShellGallery#89]
Encountered following error, while creating new policy defining:
![Screenshot (2)](https://user-images.githubusercontent.com/54034262/78883851-ad92d700-7a77-11ea-88a9-2d7b5cc1916f.png)
 The script is here:
[t1.txt](https://github.com/PowerShell/PowerShellGallery/files/4455491/t1.txt)

**Comment by SydneyhSmith** [comment]
@Neelkamal10 looks like this is an issue with the Azure PowerShell Repo, you may want to open an issue in their repo--thanks!

**Comment by Neelkamal10** [comment]
@SydneyhSmith  yes,i am stuck in this issue . Can you resolve this?

**Comment by SydneyhSmith** [comment]
@Neelkamal10 did you already open an issue in the Azure PowerShell Repo: https://github.com/Azure/azure-powershell/issues looks like the issue is from that module, not PowerShellGallery

**Comment by Neelkamal10** [comment]
@SydneyhSmith thank you for information
