### ISSUE TITLE
Orphaned Package owner cannot relink from AAD Account with same email - account claim mismatch?

### ISSUE THREAD

**Issue by teamktown** [PowerShell/PowerShellGallery#90]
PSG appears to desire an organizational email to link to Package owner and even though I have the appropriate value in place in our Azure AD and on Prem AD, I am orphaned from my Package Owner status. Package in question: https://www.powershellgallery.com/packages/ADFSToolkit/ 
When presented with sign on I was asked to create a new account despite having an existing one. 

PowerShellGallery appears to want email and yet email over the wire is being sent it looks like it is using another means connect packages.  Once an account is created 'again' because of the disconnect, no matter what adaptations to UPN in AAD and on prem AD with ADSync one cannot rejoin to the original account. Is PowerShellGallery using immutableID as well? It's unclear.
Issue was reported  via FAQ recommendations 2 days ago and want to regain connection to package and also avoid future orphaning for me or others if there are other criteria PowerShellGallery is using to match accounts to users.  If there is, the UI and FAQ would be well served to reflect that as well to enable knowledgeable users to align data more appropriately and perform the re-link themselves.

**Comment by SydneyhSmith** [comment]
@teamktown would you mind sending an email to cgadmin@microsoft.com, so that we can utilize our support channel to get this issue resolved? Thanks!

**Comment by teamktown** [comment]
Thanks @SydneyhSmith, note sent, awaiting reply.

**Comment by teamktown** [comment]
bump on this @SydneyhSmith, @edyoung. Also emailed cgadmin@microsoft.com again on it. Insight welcome on resolving this. Thanks!

**Comment by teamktown** [comment]
update: some tweaks have been done but no resolution as of yet. Hopeful to close it soon as urgency is getting stronger to do some updates

**Comment by teamktown** [comment]
Issue was resolved through the path of cgadmin@microsoft.com and the team member(s) there. Rather than place the name in the ticket (you know who you are -- Thank you you!)  following the escalation channel of the cgadmin@microsoft.com account  is the best way. Thanks for the work behind the scenes on this and the suggestion from @SydneyhSmith 
As a suggestion, maybe make this pathway guidance more visible on: https://www.powershellgallery.com/policies/Contact? It directs us to here on github issue tracker.  That would have trimmed a week off as it was submitted that way April 6th -- 6 days prior to opening this ticket here.  Had I known about that, I would have done this asap.
Again, thanks and hope the suggestion helps shorten things for others in the future.
