### ISSUE TITLE
Paging not working with filters

### ISSUE THREAD

**Issue by MichaelGrafnetter** [PowerShell/PowerShellGallery#92]
I would like to report a bug in the [package search feature](https://www.powershellgallery.com/packages). Steps to reproduce:

I start by applying a filter to the list of packages (e.g. Linux-only):

------------

![image](https://user-images.githubusercontent.com/8986376/79221913-f02d2880-7e56-11ea-9148-b841d74020f3.png)

------------

But when I try to navigate to the next page in the search results...

------------

![image](https://user-images.githubusercontent.com/8986376/79221963-01763500-7e57-11ea-9851-a99a6524df9a.png)

------------

... the filters get cleared out and all packages are shown:

------------

![image](https://user-images.githubusercontent.com/8986376/79221990-09ce7000-7e57-11ea-963f-f23ab319de03.png)

**Comment by SydneyhSmith** [comment]
Thanks @MichaelGrafnetter looks like this a duplicate-- this issue is being tracked with issue #49
