### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by spottedmahn** [PowerShell/PowerShellGallery#95]
On https://www.powershellgallery.com/ the following links are broken, `404`'s:

![image](https://user-images.githubusercontent.com/14079228/80022041-7aa20780-84a9-11ea-9da0-9bca64c6b06b.png)

---

https://docs.microsoft.com/en-us/powershell/gallery/getting-started maybe is supposed to be https://docs.microsoft.com/en-us/powershell/scripting/gallery/getting-started?

https://docs.microsoft.com/en-us/powershell/gallery/overview  and https://docs.microsoft.com/en-us/powershell/scripting/gallery/overview?

**Comment by bormm** [comment]
Seems to be fixed in the meantime.

**Comment by spottedmahn** [comment]
nice!  thanks @bormm 👍
